export { HRworksClient } from "./client.js";
export type {
  HRworksClientConfig,
  HRworksPerson,
  HRworksAddress,
  HRworksBankDetails,
  HRworksCreatePersonData,
  HRworksAbsence,
  HRworksAbsenceType,
  HRworksCreateAbsenceData,
  HRworksAbsenceBalance,
  HRworksWorkingTime,
  HRworksCreateWorkingTimeData,
  HRworksWorkingTimeModel,
  HRworksOrganizationUnit,
  HRworksCostCenter,
  HRworksHolidayCalendar,
  HRworksHoliday,
  HRworksProject,
  HRworksListResponse,
  HRworksPaginationParams,
} from "./types.js";
