import { z } from "zod";
import { CanonicalCustomer, CanonicalOrder, CanonicalOrganization, CanonicalJob, CanonicalFile } from "@opensoftware/core-types";

/**
 * Canonical event registry — the ONLY event shapes that cross module boundaries.
 *
 * Every module may publish or subscribe to these. New event types require
 * updating this file and getting the canonical-type schema extended first
 * (see @opensoftware/core-types). Modules MUST NOT invent private event
 * names that cross the pipeline.
 *
 * Event naming: `<entity>.<verb-past>` — e.g. `customer.created`, `order.placed`.
 * Always past-tense — events describe what HAS HAPPENED, not intentions.
 */

const EventMeta = z.object({
  /** Monotonic event id generated by the publisher. UUIDv7 preferred. */
  eventId: z.string().min(1),
  /** ISO-8601 timestamp when the source module wrote the native row. */
  occurredAt: z.string().datetime(),
  /** Slug of the publishing module ("openaccounting", "openmailer", ...). */
  source: z.string().min(1),
  /** Workspace scope if multi-tenant; null for workspace-agnostic events. */
  workspaceId: z.string().nullable(),
  /** Optional correlation id for tracing a chain of cascades. */
  correlationId: z.string().optional(),
  /** Optional user id of whoever triggered the event. */
  actorUserId: z.string().optional(),
});

export const CustomerCreatedEvent = EventMeta.extend({
  type: z.literal("customer.created"),
  payload: CanonicalCustomer,
});
export type CustomerCreatedEvent = z.infer<typeof CustomerCreatedEvent>;

export const CustomerUpdatedEvent = EventMeta.extend({
  type: z.literal("customer.updated"),
  payload: CanonicalCustomer,
  /** Dotted paths of fields that changed; admin UI uses this for diff views. */
  changedFields: z.array(z.string()).default([]),
});
export type CustomerUpdatedEvent = z.infer<typeof CustomerUpdatedEvent>;

export const CustomerMergedEvent = EventMeta.extend({
  type: z.literal("customer.merged"),
  payload: CanonicalCustomer,
  /** The canonical ids that were merged into `payload.id`. */
  mergedFromIds: z.array(z.string()),
});
export type CustomerMergedEvent = z.infer<typeof CustomerMergedEvent>;

export const OrganizationCreatedEvent = EventMeta.extend({
  type: z.literal("organization.created"),
  payload: CanonicalOrganization,
});
export type OrganizationCreatedEvent = z.infer<typeof OrganizationCreatedEvent>;

export const OrganizationMemberAddedEvent = EventMeta.extend({
  type: z.literal("organization.member-added"),
  organizationId: z.string(),
  userId: z.string(),
  role: z.string(),
});
export type OrganizationMemberAddedEvent = z.infer<typeof OrganizationMemberAddedEvent>;

export const OrderPlacedEvent = EventMeta.extend({
  type: z.literal("order.placed"),
  payload: CanonicalOrder,
});
export type OrderPlacedEvent = z.infer<typeof OrderPlacedEvent>;

export const OrderShippedEvent = EventMeta.extend({
  type: z.literal("order.shipped"),
  payload: CanonicalOrder,
  trackingNumber: z.string().nullable(),
});
export type OrderShippedEvent = z.infer<typeof OrderShippedEvent>;

export const JobCompletedEvent = EventMeta.extend({
  type: z.literal("job.completed"),
  payload: CanonicalJob,
});
export type JobCompletedEvent = z.infer<typeof JobCompletedEvent>;

export const JobFailedEvent = EventMeta.extend({
  type: z.literal("job.failed"),
  payload: CanonicalJob,
});
export type JobFailedEvent = z.infer<typeof JobFailedEvent>;

export const FileUploadedEvent = EventMeta.extend({
  type: z.literal("file.uploaded"),
  payload: CanonicalFile,
});
export type FileUploadedEvent = z.infer<typeof FileUploadedEvent>;

export const CanonicalEvent = z.discriminatedUnion("type", [
  CustomerCreatedEvent,
  CustomerUpdatedEvent,
  CustomerMergedEvent,
  OrganizationCreatedEvent,
  OrganizationMemberAddedEvent,
  OrderPlacedEvent,
  OrderShippedEvent,
  JobCompletedEvent,
  JobFailedEvent,
  FileUploadedEvent,
]);
export type CanonicalEvent = z.infer<typeof CanonicalEvent>;

export const CANONICAL_EVENT_TYPES = [
  "customer.created",
  "customer.updated",
  "customer.merged",
  "organization.created",
  "organization.member-added",
  "order.placed",
  "order.shipped",
  "job.completed",
  "job.failed",
  "file.uploaded",
] as const;
export type CanonicalEventType = typeof CANONICAL_EVENT_TYPES[number];
