/**
 * Parse G-code file comments to extract print metadata.
 * Works with PrusaSlicer, OrcaSlicer, and Cura output.
 */

export interface GcodeMetadata {
  estimatedTime?: number; // seconds
  filamentUsedGrams?: number;
  filamentUsedMeters?: number;
  layerCount?: number;
  layerHeight?: number;
  nozzleDiameter?: number;
  slicerName?: string;
}

/**
 * Parse G-code content for metadata.
 * Scans both the first N and last N lines (metadata may appear at header or footer).
 * Only reads comment lines starting with ; or @
 */
export function parseGcodeMetadata(
  content: string,
  maxLines = 500,
): GcodeMetadata {
  const result: GcodeMetadata = {};
  const allLines = content.split("\n");
  // Scan first N lines (header) and last N lines (footer) for metadata
  const headerLines = allLines.slice(0, maxLines);
  const footerLines = allLines.length > maxLines
    ? allLines.slice(-maxLines)
    : [];
  const lines = [...headerLines, ...footerLines];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed.startsWith(";") && !trimmed.startsWith("@")) continue;

    const comment = trimmed.replace(/^[;@]\s*/, "");

    // PrusaSlicer/OrcaSlicer patterns
    const timeMatch = comment.match(
      /estimated printing time.*?=\s*(.+)/i,
    );
    if (timeMatch) {
      result.estimatedTime = parseTimeString(timeMatch[1]);
    }

    const filamentGMatch = comment.match(
      /total filament used\s*\[g\]\s*[:=]\s*([\d.]+)/i,
    );
    if (filamentGMatch) {
      result.filamentUsedGrams = parseFloat(filamentGMatch[1]);
    }

    const filamentMMatch = comment.match(
      /total filament used\s*\[m\]\s*[:=]\s*([\d.]+)/i,
    );
    if (filamentMMatch) {
      result.filamentUsedMeters = parseFloat(filamentMMatch[1]);
    }

    const layerCountMatch = comment.match(/total layers?\s*[:=]\s*(\d+)/i);
    if (layerCountMatch) {
      result.layerCount = parseInt(layerCountMatch[1]);
    }

    const layerHeightMatch = comment.match(
      /layer_height\s*[:=]\s*([\d.]+)/i,
    );
    if (layerHeightMatch) {
      result.layerHeight = parseFloat(layerHeightMatch[1]);
    }

    const nozzleMatch = comment.match(
      /nozzle_diameter\s*[:=]\s*([\d.]+)/i,
    );
    if (nozzleMatch) {
      result.nozzleDiameter = parseFloat(nozzleMatch[1]);
    }

    const slicerMatch = comment.match(/generated by\s+(.+)/i);
    if (slicerMatch) {
      result.slicerName = slicerMatch[1].trim();
    }
  }

  return result;
}

/**
 * Parse time strings like "1h 23m 45s" or "1d 2h 30m" to seconds.
 */
function parseTimeString(timeStr: string): number {
  let seconds = 0;
  const days = timeStr.match(/(\d+)\s*d/);
  const hours = timeStr.match(/(\d+)\s*h/);
  const minutes = timeStr.match(/(\d+)\s*m/);
  const secs = timeStr.match(/(\d+)\s*s/);

  if (days) seconds += parseInt(days[1]) * 86400;
  if (hours) seconds += parseInt(hours[1]) * 3600;
  if (minutes) seconds += parseInt(minutes[1]) * 60;
  if (secs) seconds += parseInt(secs[1]);

  return seconds;
}
