export { TextractClient } from "./client.js";
export type {
  TextractClientConfig,
  TextractFeatureType,
  BlockType,
  EntityType,
  SelectionStatus,
  ExpenseType,
  BoundingBox,
  Point,
  Geometry,
  S3Object,
  DocumentInput,
  Relationship,
  Block,
  KeyValuePair,
  ExpenseFieldType,
  ExpenseField,
  LineItemField,
  LineItemGroup,
  ExpenseDocument,
  AnalyzeDocumentRequest,
  AnalyzeDocumentResponse,
  DetectDocumentTextRequest,
  DetectDocumentTextResponse,
  AnalyzeExpenseRequest,
  AnalyzeExpenseResponse,
} from "./types.js";
