"""cam-toolpath: CNC toolpath generation using PyCAM (GPL subprocess)."""
import os
import subprocess
import tempfile
import re


def handle(params: dict) -> dict:
    input_path = params.get('inputPath', '')
    tool_diameter = params.get('toolDiameter', 3.0)
    step_down = params.get('stepDown', 1.0)
    strategy = params.get('strategy', 'roughing')

    if not input_path or not os.path.exists(input_path):
        raise FileNotFoundError(f'Input file not found: {input_path}')

    output_path = input_path.rsplit('.', 1)[0] + '.gcode'

    # PyCAM is GPL — MUST run as subprocess, never import
    try:
        result = subprocess.run([
            'pycam',
            input_path,
            '--export-gcode', output_path,
            '--tool-shape', 'cylindrical',
            '--tool-size', str(tool_diameter),
            '--process-path-strategy', _map_strategy(strategy),
            '--bounds-type', 'minimum',
            '--step-down', str(step_down),
        ], capture_output=True, text=True, timeout=120)

        if result.returncode != 0:
            raise RuntimeError(f'PyCAM failed: {result.stderr[:500]}')

    except FileNotFoundError:
        # PyCAM not installed — generate basic G-code manually
        return _generate_basic_gcode(input_path, output_path, tool_diameter, step_down, strategy)

    # Parse G-code for stats
    gcode = ''
    if os.path.exists(output_path):
        with open(output_path, 'r') as f:
            gcode = f.read()

    stats = _parse_gcode_stats(gcode)

    return {
        'gcode': gcode,
        'estimatedTime': stats['time'],
        'toolpathLength': stats['length'],
        'success': True,
    }


def _map_strategy(strategy: str) -> str:
    mapping = {
        'roughing': 'PushCutter',
        'finishing': 'DropCutter',
        'contour': 'Contour',
        'pocket': 'PushCutter',
    }
    return mapping.get(strategy, 'PushCutter')


def _generate_basic_gcode(input_path, output_path, tool_diameter, step_down, strategy):
    """Fallback: generate simple surfacing G-code without PyCAM."""
    import trimesh
    mesh = trimesh.load(input_path)
    bounds = mesh.bounds  # [[minx,miny,minz],[maxx,maxy,maxz]]

    lines = [
        '; Generated by Open3D CAM (basic mode)',
        f'; Tool: {tool_diameter}mm, Step down: {step_down}mm',
        f'; Strategy: {strategy}',
        'G21 ; mm mode',
        'G90 ; absolute positioning',
        'G28 ; home',
        f'S12000 M3 ; spindle on',
        f'G0 Z10 ; safety height',
    ]

    min_x, min_y, min_z = bounds[0]
    max_x, max_y, max_z = bounds[1]
    step_over = tool_diameter * 0.5
    total_length = 0

    z = max_z
    while z >= min_z:
        y = min_y
        forward = True
        while y <= max_y:
            if forward:
                lines.append(f'G0 X{min_x:.3f} Y{y:.3f}')
                lines.append(f'G1 Z{z:.3f} F200')
                lines.append(f'G1 X{max_x:.3f} F800')
                total_length += max_x - min_x
            else:
                lines.append(f'G0 X{max_x:.3f} Y{y:.3f}')
                lines.append(f'G1 Z{z:.3f} F200')
                lines.append(f'G1 X{min_x:.3f} F800')
                total_length += max_x - min_x
            lines.append(f'G0 Z{z + 2:.3f}')
            y += step_over
            forward = not forward
        z -= step_down

    lines.extend(['G0 Z20', 'M5 ; spindle off', 'G28', 'M2'])
    gcode = '\n'.join(lines)

    with open(output_path, 'w') as f:
        f.write(gcode)

    return {
        'gcode': gcode,
        'estimatedTime': total_length / 800 * 60,
        'toolpathLength': total_length,
        'success': True,
    }


def _parse_gcode_stats(gcode: str) -> dict:
    total_length = 0.0
    last_x, last_y, last_z = 0.0, 0.0, 0.0
    feed_rate = 800.0

    for line in gcode.split('\n'):
        line = line.strip()
        if not line or line.startswith(';'):
            continue
        if line.startswith('G1') or line.startswith('G0'):
            x = _extract_value(line, 'X', last_x)
            y = _extract_value(line, 'Y', last_y)
            z = _extract_value(line, 'Z', last_z)
            f = _extract_value(line, 'F', feed_rate)
            dist = ((x - last_x)**2 + (y - last_y)**2 + (z - last_z)**2)**0.5
            total_length += dist
            if f > 0:
                feed_rate = f
            last_x, last_y, last_z = x, y, z

    est_time = total_length / (feed_rate / 60) if feed_rate > 0 else 0
    return {'length': total_length, 'time': est_time}


def _extract_value(line: str, letter: str, default: float) -> float:
    match = re.search(f'{letter}([\\-\\d.]+)', line)
    return float(match.group(1)) if match else default
