/**
 * opencam — G-code post processor.
 *
 * String-template renderer that expands a small set of placeholders against
 * a ToolpathResult + tool / op metadata. Keeps dialect specifics inside the
 * template string so multiple dialects (grbl, fanuc, linuxcnc, marlin, haas,
 * mach3) can share this single renderer.
 *
 * Template placeholders (case-sensitive):
 *   {TOOL_NAME}        — human-readable tool name
 *   {TOOL_DIAMETER}    — tool diameter in mm (3 decimals)
 *   {FEED}             — feedrate in mm/min (integer)
 *   {RPM}              — spindle RPM (integer)
 *   {OP_KIND}          — operation kind (e.g. "face", "contour")
 *   {STOCK_X}/{Y}/{Z}  — stock bounding dimensions in mm (3 decimals)
 *   {TOOLPATH_GCODE}   — sentinel replaced with per-line G0/G1 moves
 *
 * Per-line emission:
 *   - Rapid (G0) between polylines at safe Z = stock.max.z + 5 mm.
 *   - Linear (G1) within a polyline at the configured feedrate.
 *   - All coordinates rounded to 3 decimal places.
 *
 * M1 does NOT emit dialect-specific prologue/epilogue — that's the template's
 * responsibility. Warnings are accumulated when the rendered gcode contains
 * obviously dangerous conditions (empty toolpath, missing placeholders,
 * spindle RPM = 0, etc.) and returned to the caller.
 */

import type { BBox3, ToolpathResult } from "./cam-kernel";

export type OperationKind =
  | "face"
  | "contour"
  | "pocket"
  | "drill"
  | "adaptive"
  | "3d-parallel";

export interface GcodeLine {
  cmd: string;
  comment?: string;
}

export interface PostRenderInput {
  toolpath: ToolpathResult;
  tool: { id: string; name: string; diameterMm: number };
  op: { kind: OperationKind; feedMmMin: number; spindleRpm: number };
  stock: BBox3;
}

export interface PostRenderResult {
  gcode: string;
  lineCount: number;
  estimatedDurationSec: number;
  bbox: BBox3;
  warnings: string[];
}

function round3(n: number): string {
  if (!Number.isFinite(n)) return "0.000";
  return n.toFixed(3);
}

/** Render the TOOLPATH_GCODE sentinel expansion. */
function emitMoves(input: PostRenderInput): { text: string; lineCount: number } {
  const { toolpath, op, stock } = input;
  const feed = Math.max(1, Math.round(op.feedMmMin));
  const safeZ = stock.max.z + 5;
  const lines: string[] = [];
  for (const line of toolpath.polylines) {
    if (line.length === 0) continue;
    // Rapid to first point at safe Z, then plunge to cut Z.
    const first = line[0];
    lines.push(`G0 Z${round3(safeZ)}`);
    lines.push(`G0 X${round3(first.x)} Y${round3(first.y)}`);
    lines.push(`G1 Z${round3(first.z)} F${feed}`);
    for (let i = 1; i < line.length; i += 1) {
      const p = line[i];
      lines.push(`G1 X${round3(p.x)} Y${round3(p.y)} Z${round3(p.z)} F${feed}`);
    }
    // Retract to safe Z after each polyline.
    lines.push(`G0 Z${round3(safeZ)}`);
  }
  return { text: lines.join("\n"), lineCount: lines.length };
}

/**
 * Render a G-code program from a template + toolpath. Returns the rendered
 * string, a line count, estimated duration (seconds) copied from the
 * toolpath, the bbox, and any warnings surfaced during rendering.
 */
export function renderGcode(tpl: string, input: PostRenderInput): PostRenderResult {
  const warnings: string[] = [];
  const { toolpath, tool, op, stock } = input;

  if (toolpath.polylines.length === 0) {
    warnings.push("toolpath has no polylines — emitting header only");
  }
  if (op.spindleRpm <= 0) {
    warnings.push("spindleRpm <= 0 — spindle will not start");
  }
  if (op.feedMmMin <= 0) {
    warnings.push("feedMmMin <= 0 — defaulting to 1 mm/min in emitted gcode");
  }
  if (tool.diameterMm <= 0) {
    warnings.push("toolDiameterMm <= 0 — template rendering may be misleading");
  }

  const stockX = stock.max.x - stock.min.x;
  const stockY = stock.max.y - stock.min.y;
  const stockZ = stock.max.z - stock.min.z;
  const header = `; Generated by OpenCAM — ${op.kind} via tool ${tool.name} Ø${round3(tool.diameterMm)}mm`;

  const moves = emitMoves(input);

  const replacements: Record<string, string> = {
    "{TOOL_NAME}": tool.name,
    "{TOOL_DIAMETER}": round3(tool.diameterMm),
    "{FEED}": String(Math.max(1, Math.round(op.feedMmMin))),
    "{RPM}": String(Math.max(0, Math.round(op.spindleRpm))),
    "{OP_KIND}": op.kind,
    "{STOCK_X}": round3(stockX),
    "{STOCK_Y}": round3(stockY),
    "{STOCK_Z}": round3(stockZ),
    "{TOOLPATH_GCODE}": moves.text,
  };

  let body = tpl;
  for (const [key, value] of Object.entries(replacements)) {
    body = body.split(key).join(value);
  }

  // Warn about any unresolved placeholders that looked like {FOO}.
  const unresolved = body.match(/\{[A-Z_]+\}/g);
  if (unresolved && unresolved.length > 0) {
    const uniq = Array.from(new Set(unresolved));
    warnings.push(`unresolved template placeholders: ${uniq.join(", ")}`);
  }

  const gcode = `${header}\n${body}\n`;
  const lineCount = gcode.split("\n").length - 1;

  return {
    gcode,
    lineCount,
    estimatedDurationSec: toolpath.estimatedDurationSec,
    bbox: toolpath.bbox,
    warnings,
  };
}

/** Helper: emit a sequence of typed GcodeLine objects into a plain string. */
export function linesToText(lines: GcodeLine[]): string {
  return lines
    .map((l) => (l.comment ? `${l.cmd} ; ${l.comment}` : l.cmd))
    .join("\n");
}
