export { DpdClient } from "./client.js";
export type {
  DpdProduct,
  DpdLabelFormat,
  DpdLabelSize,
  DpdTrackingStatus,
  DpdAddress,
  DpdParcel,
  DpdServices,
  DpdCustomsInfo,
  DpdCustomsItem,
  DpdShipmentRequest,
  DpdShipmentResponse,
  DpdParcelResponse,
  DpdTrackingResponse,
  DpdTrackingEvent,
  DpdLabelRequest,
  DpdPickupRequest,
  DpdPickupResponse,
  DpdAuthToken,
  DpdClientConfig,
} from "./types.js";
