export { HubSpotClient } from "./client.js";
export {
  verifyHubSpotWebhook,
  verifyHubSpotWebhookV1,
  parseHubSpotWebhookEvents,
  isHubSpotWebhookSubscriptionType,
} from "./webhooks.js";
export type { HubSpotWebhookConfig } from "./webhooks.js";
export type {
  HubSpotClientConfig,
  HubSpotCrmObject,
  HubSpotAssociationResult,
  HubSpotPaginatedResponse,
  HubSpotBatchResponse,
  HubSpotSearchRequest,
  HubSpotFilterOperator,
  HubSpotContact,
  HubSpotContactProperties,
  HubSpotCreateContactInput,
  HubSpotUpdateContactInput,
  HubSpotCompany,
  HubSpotCompanyProperties,
  HubSpotCreateCompanyInput,
  HubSpotUpdateCompanyInput,
  HubSpotDeal,
  HubSpotDealProperties,
  HubSpotCreateDealInput,
  HubSpotUpdateDealInput,
  HubSpotEmail,
  HubSpotEmailProperties,
  HubSpotCreateEmailInput,
  HubSpotList,
  HubSpotListsResponse,
  HubSpotListMembersResponse,
  HubSpotCreateListInput,
  HubSpotAssociationInput,
  HubSpotWebhookEvent,
  HubSpotWebhookSubscriptionType,
  HubSpotPaginationParams,
} from "./types.js";
