import type { IntegrationDefinition } from "../core/types.js";

/**
 * Registry of all 100 supported external API integrations.
 * Organized by app category.
 */
export const INTEGRATION_REGISTRY: Record<string, IntegrationDefinition> = {

  // ==================== OpenAccounting: Payment (1-10) ====================

  stripe: {
    id: "stripe",
    name: "Stripe",
    description: "Zahlungsabwicklung, Rechnungen bezahlen",
    apps: ["openaccounting"],
    category: "payment",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 100,
    requiredEnvVars: ["STRIPE_SECRET_KEY"],
    optionalEnvVars: ["STRIPE_WEBHOOK_SECRET", "STRIPE_PUBLISHABLE_KEY"],
    baseUrl: "https://api.stripe.com/v1",
    docsUrl: "https://stripe.com/docs/api",
    icon: "stripe",
  },

  paypal: {
    id: "paypal",
    name: "PayPal Business",
    description: "Zahlungseingang, Transaktionsabgleich",
    apps: ["openaccounting"],
    category: "payment",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 30,
    requiredEnvVars: ["PAYPAL_CLIENT_ID", "PAYPAL_CLIENT_SECRET"],
    baseUrl: "https://api-m.paypal.com/v2",
    docsUrl: "https://developer.paypal.com/docs/api/overview/",
    icon: "paypal",
    oauthAuthUrl: "https://www.paypal.com/signin/authorize",
    oauthTokenUrl: "https://api-m.paypal.com/v1/oauth2/token",
  },

  klarna: {
    id: "klarna",
    name: "Klarna",
    description: "Zahlungsabwicklung (Buy now, pay later)",
    apps: ["openaccounting"],
    category: "payment",
    authType: "basic_auth",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["KLARNA_USERNAME", "KLARNA_PASSWORD"],
    baseUrl: "https://api.klarna.com",
    docsUrl: "https://docs.klarna.com/",
    icon: "klarna",
  },

  mollie: {
    id: "mollie",
    name: "Mollie",
    description: "Multi-Payment-Gateway (EU-fokussiert)",
    apps: ["openaccounting"],
    category: "payment",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 250,
    requiredEnvVars: ["MOLLIE_API_KEY"],
    baseUrl: "https://api.mollie.com/v2",
    docsUrl: "https://docs.mollie.com/",
    icon: "mollie",
  },

  sumup: {
    id: "sumup",
    name: "SumUp",
    description: "Kartenzahlungen (POS)",
    apps: ["openaccounting"],
    category: "payment",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["SUMUP_CLIENT_ID", "SUMUP_CLIENT_SECRET"],
    baseUrl: "https://api.sumup.com/v0.1",
    docsUrl: "https://developer.sumup.com/docs/api/",
    icon: "sumup",
    oauthAuthUrl: "https://api.sumup.com/authorize",
    oauthTokenUrl: "https://api.sumup.com/token",
  },

  amazon_pay: {
    id: "amazon_pay",
    name: "Amazon Pay",
    description: "Zahlungsabwicklung via Amazon",
    apps: ["openaccounting"],
    category: "payment",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["AMAZON_PAY_PUBLIC_KEY_ID", "AMAZON_PAY_PRIVATE_KEY", "AMAZON_PAY_MERCHANT_ID"],
    baseUrl: "https://pay-api.amazon.eu/v2",
    docsUrl: "https://developer.amazon.com/docs/amazon-pay-api-v2/introduction.html",
    icon: "amazon_pay",
  },

  apple_pay: {
    id: "apple_pay",
    name: "Apple Pay",
    description: "Zahlungsabwicklung via Apple",
    apps: ["openaccounting"],
    category: "payment",
    authType: "custom",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["APPLE_PAY_MERCHANT_ID", "APPLE_PAY_CERTIFICATE"],
    baseUrl: "https://apple-pay-gateway.apple.com/paymentservices",
    docsUrl: "https://developer.apple.com/documentation/apple_pay_on_the_web",
    icon: "apple_pay",
  },

  google_pay: {
    id: "google_pay",
    name: "Google Pay",
    description: "Zahlungsabwicklung via Google",
    apps: ["openaccounting"],
    category: "payment",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["GOOGLE_PAY_MERCHANT_ID"],
    baseUrl: "https://pay.google.com/gp/p",
    docsUrl: "https://developers.google.com/pay/api",
    icon: "google_pay",
  },

  // ==================== OpenAccounting: Banking (11-17) ====================

  plaid: {
    id: "plaid",
    name: "Plaid / FinTS",
    description: "Bankkonto-Anbindung, Transaktionsimport",
    apps: ["openaccounting"],
    category: "banking",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 120,
    requiredEnvVars: ["PLAID_CLIENT_ID", "PLAID_SECRET"],
    optionalEnvVars: ["PLAID_ENV"],
    baseUrl: "https://production.plaid.com",
    docsUrl: "https://plaid.com/docs/",
    icon: "plaid",
  },

  gocardless: {
    id: "gocardless",
    name: "GoCardless (Open Banking)",
    description: "SEPA-Lastschriften, Bankdaten-Sync",
    apps: ["openaccounting"],
    category: "banking",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["GOCARDLESS_ACCESS_TOKEN"],
    baseUrl: "https://api.gocardless.com",
    docsUrl: "https://developer.gocardless.com/",
    icon: "gocardless",
  },

  wise: {
    id: "wise",
    name: "Wise (TransferWise)",
    description: "Internationale Überweisungen",
    apps: ["openaccounting"],
    category: "banking",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["WISE_API_TOKEN"],
    baseUrl: "https://api.transferwise.com/v3",
    docsUrl: "https://docs.wise.com/api-docs/",
    icon: "wise",
  },

  vivid: {
    id: "vivid",
    name: "Vivid Money",
    description: "Geschäftskonto-Anbindung",
    apps: ["openaccounting"],
    category: "banking",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["VIVID_CLIENT_ID", "VIVID_CLIENT_SECRET"],
    baseUrl: "https://api.vivid.money/v1",
    docsUrl: "https://vivid.money/business",
    icon: "vivid",
    oauthAuthUrl: "https://api.vivid.money/oauth2/authorize",
    oauthTokenUrl: "https://api.vivid.money/oauth2/token",
  },

  n26: {
    id: "n26",
    name: "N26 Business",
    description: "Geschäftskonto-Anbindung",
    apps: ["openaccounting"],
    category: "banking",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["N26_CLIENT_ID", "N26_CLIENT_SECRET"],
    baseUrl: "https://api.tech26.de/api",
    docsUrl: "https://docs.tech26.de/",
    icon: "n26",
    oauthAuthUrl: "https://api.tech26.de/oauth2/authorize",
    oauthTokenUrl: "https://api.tech26.de/oauth2/token",
  },

  commerzbank: {
    id: "commerzbank",
    name: "Commerzbank API",
    description: "Banking-Integration (PSD2)",
    apps: ["openaccounting"],
    category: "banking",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["COMMERZBANK_CLIENT_ID", "COMMERZBANK_CLIENT_SECRET"],
    baseUrl: "https://api.commerzbank.com/accounts-api/v1",
    docsUrl: "https://developer.commerzbank.com/",
    icon: "commerzbank",
    oauthAuthUrl: "https://api.commerzbank.com/auth/realms/CBAPI/protocol/openid-connect/auth",
    oauthTokenUrl: "https://api.commerzbank.com/auth/realms/CBAPI/protocol/openid-connect/token",
  },

  deutsche_bank: {
    id: "deutsche_bank",
    name: "Deutsche Bank API",
    description: "Banking-Integration (PSD2)",
    apps: ["openaccounting"],
    category: "banking",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["DEUTSCHE_BANK_CLIENT_ID", "DEUTSCHE_BANK_CLIENT_SECRET"],
    baseUrl: "https://api.db.com/gw/dbapi/banking/v2",
    docsUrl: "https://developer.db.com/",
    icon: "deutsche_bank",
    oauthAuthUrl: "https://api.db.com/gw/oidc/authorize",
    oauthTokenUrl: "https://api.db.com/gw/oidc/token",
  },

  sparkasse_fints: {
    id: "sparkasse_fints",
    name: "Sparkasse (FinTS/HBCI)",
    description: "Banking-Integration via FinTS",
    apps: ["openaccounting"],
    category: "banking",
    authType: "custom",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: ["FINTS_BANK_URL", "FINTS_BANK_CODE", "FINTS_USERNAME", "FINTS_PIN"],
    baseUrl: "https://banking-hb.s-fints-pt-hb.de/fints30",
    docsUrl: "https://www.hbci-zka.de/",
    icon: "sparkasse",
  },

  // ==================== OpenAccounting: Tax & Compliance (18-21) ====================

  datev: {
    id: "datev",
    name: "DATEV Connect",
    description: "Buchhaltungsexport/-import (deutscher Standard)",
    apps: ["openaccounting"],
    category: "tax",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["DATEV_CLIENT_ID", "DATEV_CLIENT_SECRET"],
    baseUrl: "https://api.datev.de/platform/v1",
    docsUrl: "https://developer.datev.de/",
    icon: "datev",
    oauthAuthUrl: "https://login.datev.de/openidsso/authorize",
    oauthTokenUrl: "https://api.datev.de/token",
    oauthScopes: ["openid", "datev:accounting:clients"],
  },

  elster: {
    id: "elster",
    name: "ELSTER (ERiC)",
    description: "USt-VA, Steuererklärungen ans Finanzamt",
    apps: ["openaccounting", "openpayroll"],
    category: "tax",
    authType: "custom",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: ["ELSTER_CERTIFICATE_PATH", "ELSTER_CERTIFICATE_PIN"],
    baseUrl: "https://www.elster.de/elsterweb/softwarehersteller",
    docsUrl: "https://www.elster.de/elsterweb/entwickler",
    icon: "elster",
  },

  vies_vat: {
    id: "vies_vat",
    name: "VIES VAT Validation",
    description: "EU-USt-ID-Validierung",
    apps: ["openaccounting"],
    category: "tax",
    authType: "none",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: [],
    baseUrl: "https://ec.europa.eu/taxation_customs/vies/rest-api",
    docsUrl: "https://ec.europa.eu/taxation_customs/vies/",
    icon: "eu",
  },

  bzst: {
    id: "bzst",
    name: "BZSt (Bundeszentralamt)",
    description: "Zusammenfassende Meldung",
    apps: ["openaccounting"],
    category: "tax",
    authType: "custom",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: ["BZST_CERTIFICATE_PATH", "BZST_CERTIFICATE_PIN"],
    baseUrl: "https://www.bzst.de/SiteGlobals/Functions",
    docsUrl: "https://www.bzst.de/",
    icon: "bzst",
  },

  // ==================== OpenAccounting: E-Invoicing (22-23) ====================

  zugferd: {
    id: "zugferd",
    name: "ZUGFeRD / XRechnung",
    description: "E-Invoicing (deutscher/EU-Standard)",
    apps: ["openaccounting"],
    category: "invoicing",
    authType: "none",
    webhooks: false,
    rateLimitRPM: 1000,
    requiredEnvVars: [],
    baseUrl: "https://www.xrechnung.de",
    docsUrl: "https://www.ferd-net.de/",
    icon: "zugferd",
  },

  peppol: {
    id: "peppol",
    name: "Peppol",
    description: "EU-weites E-Invoicing-Netzwerk",
    apps: ["openaccounting"],
    category: "invoicing",
    authType: "custom",
    webhooks: true,
    rateLimitRPM: 30,
    requiredEnvVars: ["PEPPOL_AP_URL", "PEPPOL_CERTIFICATE"],
    baseUrl: "https://peppol.eu/",
    docsUrl: "https://peppol.org/documentation/",
    icon: "peppol",
  },

  // ==================== OpenAccounting: ERP Sync (24-27) ====================

  lexoffice: {
    id: "lexoffice",
    name: "Lexoffice API",
    description: "Import/Export zu Lexware",
    apps: ["openaccounting"],
    category: "erp",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 120,
    requiredEnvVars: ["LEXOFFICE_API_KEY"],
    baseUrl: "https://api.lexoffice.io/v1",
    docsUrl: "https://developers.lexoffice.io/docs/",
    icon: "lexoffice",
  },

  sevdesk: {
    id: "sevdesk",
    name: "sevDesk API",
    description: "Import/Export zu sevDesk",
    apps: ["openaccounting"],
    category: "erp",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["SEVDESK_API_TOKEN"],
    baseUrl: "https://my.sevdesk.de/api/v1",
    docsUrl: "https://api.sevdesk.de/",
    icon: "sevdesk",
  },

  sap_business_one: {
    id: "sap_business_one",
    name: "SAP Business One",
    description: "Enterprise-ERP-Sync",
    apps: ["openaccounting"],
    category: "erp",
    authType: "basic_auth",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["SAP_B1_URL", "SAP_B1_COMPANY", "SAP_B1_USERNAME", "SAP_B1_PASSWORD"],
    baseUrl: "https://localhost:50000/b1s/v1",
    docsUrl: "https://help.sap.com/docs/SAP_BUSINESS_ONE",
    icon: "sap",
  },

  dynamics365: {
    id: "dynamics365",
    name: "Microsoft Dynamics 365",
    description: "Enterprise-ERP-Sync",
    apps: ["openaccounting"],
    category: "erp",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["DYNAMICS_CLIENT_ID", "DYNAMICS_CLIENT_SECRET", "DYNAMICS_TENANT_ID"],
    baseUrl: "https://api.businesscentral.dynamics.com/v2.0",
    docsUrl: "https://learn.microsoft.com/en-us/dynamics365/",
    icon: "microsoft",
    oauthAuthUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    oauthTokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
  },

  billomat: {
    id: "billomat",
    name: "Billomat API",
    description: "Rechnungstool-Import",
    apps: ["openaccounting"],
    category: "erp",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 150,
    requiredEnvVars: ["BILLOMAT_API_KEY", "BILLOMAT_SUBDOMAIN"],
    baseUrl: "https://my.billomat.net/api",
    docsUrl: "https://www.billomat.com/api/",
    icon: "billomat",
  },

  fastbill: {
    id: "fastbill",
    name: "FastBill API",
    description: "Rechnungstool-Import",
    apps: ["openaccounting"],
    category: "erp",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["FASTBILL_EMAIL", "FASTBILL_API_KEY"],
    baseUrl: "https://my.fastbill.com/api/1.0/api.php",
    docsUrl: "https://apidocs.fastbill.com/",
    icon: "fastbill",
  },

  // ==================== OpenAccounting: OCR & AI (28-32) ====================

  aws_textract: {
    id: "aws_textract",
    name: "AWS Textract",
    description: "OCR für Belege/Rechnungen",
    apps: ["openaccounting"],
    category: "ocr",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION"],
    baseUrl: "https://textract.eu-central-1.amazonaws.com",
    docsUrl: "https://docs.aws.amazon.com/textract/",
    icon: "aws",
  },

  google_document_ai: {
    id: "google_document_ai",
    name: "Google Document AI",
    description: "OCR für Belege/Rechnungen",
    apps: ["openaccounting"],
    category: "ocr",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["GOOGLE_CLOUD_PROJECT_ID", "GOOGLE_CLOUD_CREDENTIALS"],
    baseUrl: "https://eu-documentai.googleapis.com/v1",
    docsUrl: "https://cloud.google.com/document-ai/docs",
    icon: "google_cloud",
    oauthTokenUrl: "https://oauth2.googleapis.com/token",
  },

  openai: {
    id: "openai",
    name: "OpenAI API",
    description: "AI-Buchungsassistent, Dokumentenanalyse",
    apps: ["openaccounting", "openlawyer", "opensem"],
    category: "ai",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["OPENAI_API_KEY"],
    baseUrl: "https://api.openai.com/v1",
    docsUrl: "https://platform.openai.com/docs/",
    icon: "openai",
  },

  anthropic: {
    id: "anthropic",
    name: "Anthropic Claude API",
    description: "AI-Buchungsassistent (Alternative)",
    apps: ["openaccounting", "openlawyer", "opensem"],
    category: "ai",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["ANTHROPIC_API_KEY"],
    baseUrl: "https://api.anthropic.com/v1",
    docsUrl: "https://docs.anthropic.com/",
    icon: "anthropic",
  },

  // ==================== OpenMailer: Email Delivery (33-38) ====================

  sendgrid: {
    id: "sendgrid",
    name: "SendGrid",
    description: "Transaktionaler E-Mail-Versand",
    apps: ["openmailer"],
    category: "email_delivery",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 600,
    requiredEnvVars: ["SENDGRID_API_KEY"],
    baseUrl: "https://api.sendgrid.com/v3",
    docsUrl: "https://docs.sendgrid.com/",
    icon: "sendgrid",
  },

  aws_ses: {
    id: "aws_ses",
    name: "AWS SES",
    description: "E-Mail-Versand (hohe Volumina)",
    apps: ["openmailer"],
    category: "email_delivery",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 100,
    requiredEnvVars: ["AWS_SES_ACCESS_KEY_ID", "AWS_SES_SECRET_ACCESS_KEY", "AWS_SES_REGION"],
    baseUrl: "https://email.eu-central-1.amazonaws.com",
    docsUrl: "https://docs.aws.amazon.com/ses/",
    icon: "aws",
  },

  mailgun: {
    id: "mailgun",
    name: "Mailgun",
    description: "E-Mail-Versand + Bounce-Handling",
    apps: ["openmailer"],
    category: "email_delivery",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 300,
    requiredEnvVars: ["MAILGUN_API_KEY", "MAILGUN_DOMAIN"],
    baseUrl: "https://api.eu.mailgun.net/v3",
    docsUrl: "https://documentation.mailgun.com/",
    icon: "mailgun",
  },

  postmark: {
    id: "postmark",
    name: "Postmark",
    description: "Transaktionaler E-Mail-Versand",
    apps: ["openmailer"],
    category: "email_delivery",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 300,
    requiredEnvVars: ["POSTMARK_SERVER_TOKEN"],
    baseUrl: "https://api.postmarkapp.com",
    docsUrl: "https://postmarkapp.com/developer",
    icon: "postmark",
  },

  resend: {
    id: "resend",
    name: "Resend",
    description: "Moderner E-Mail-Versand",
    apps: ["openmailer"],
    category: "email_delivery",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 100,
    requiredEnvVars: ["RESEND_API_KEY"],
    baseUrl: "https://api.resend.com",
    docsUrl: "https://resend.com/docs",
    icon: "resend",
  },

  brevo: {
    id: "brevo",
    name: "Brevo (Sendinblue)",
    description: "E-Mail-Marketing + Transactional",
    apps: ["openmailer"],
    category: "email_delivery",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 100,
    requiredEnvVars: ["BREVO_API_KEY"],
    baseUrl: "https://api.brevo.com/v3",
    docsUrl: "https://developers.brevo.com/",
    icon: "brevo",
  },

  // ==================== OpenMailer: CRM & Marketing (39-42) ====================

  mailchimp: {
    id: "mailchimp",
    name: "Mailchimp",
    description: "Newsletter-Import/Export",
    apps: ["openmailer"],
    category: "email_marketing",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 10,
    requiredEnvVars: ["MAILCHIMP_API_KEY"],
    optionalEnvVars: ["MAILCHIMP_SERVER_PREFIX"],
    baseUrl: "https://us1.api.mailchimp.com/3.0",
    docsUrl: "https://mailchimp.com/developer/",
    icon: "mailchimp",
    oauthAuthUrl: "https://login.mailchimp.com/oauth2/authorize",
    oauthTokenUrl: "https://login.mailchimp.com/oauth2/token",
  },

  cleverreach: {
    id: "cleverreach",
    name: "CleverReach",
    description: "Newsletter-Import/Export (DE-Markt)",
    apps: ["openmailer"],
    category: "email_marketing",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["CLEVERREACH_CLIENT_ID", "CLEVERREACH_CLIENT_SECRET"],
    baseUrl: "https://rest.cleverreach.com/v3",
    docsUrl: "https://rest.cleverreach.com/explorer/",
    icon: "cleverreach",
    oauthAuthUrl: "https://rest.cleverreach.com/oauth/authorize.php",
    oauthTokenUrl: "https://rest.cleverreach.com/oauth/token.php",
  },

  hubspot: {
    id: "hubspot",
    name: "HubSpot",
    description: "CRM-Kontakt-Sync",
    apps: ["openmailer"],
    category: "crm",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 100,
    requiredEnvVars: ["HUBSPOT_CLIENT_ID", "HUBSPOT_CLIENT_SECRET"],
    baseUrl: "https://api.hubapi.com",
    docsUrl: "https://developers.hubspot.com/docs/api/overview",
    icon: "hubspot",
    oauthAuthUrl: "https://app.hubspot.com/oauth/authorize",
    oauthTokenUrl: "https://api.hubapi.com/oauth/v1/token",
    oauthScopes: ["crm.objects.contacts.read", "crm.objects.contacts.write"],
  },

  // ==================== OpenMailer: Validation & Communication (43-47) ====================

  clearbit: {
    id: "clearbit",
    name: "Clearbit",
    description: "E-Mail-Validierung + Enrichment",
    apps: ["openmailer"],
    category: "crm",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 600,
    requiredEnvVars: ["CLEARBIT_API_KEY"],
    baseUrl: "https://person.clearbit.com/v2",
    docsUrl: "https://clearbit.com/docs",
    icon: "clearbit",
  },

  hunter: {
    id: "hunter",
    name: "Hunter.io",
    description: "E-Mail-Finder + Verifikation",
    apps: ["openmailer"],
    category: "crm",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["HUNTER_API_KEY"],
    baseUrl: "https://api.hunter.io/v2",
    docsUrl: "https://hunter.io/api-documentation",
    icon: "hunter",
  },

  zerobounce: {
    id: "zerobounce",
    name: "ZeroBounce",
    description: "E-Mail-Validierung",
    apps: ["openmailer"],
    category: "crm",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 100,
    requiredEnvVars: ["ZEROBOUNCE_API_KEY"],
    baseUrl: "https://api.zerobounce.net/v2",
    docsUrl: "https://www.zerobounce.net/docs/",
    icon: "zerobounce",
  },

  twilio: {
    id: "twilio",
    name: "Twilio",
    description: "SMS-Benachrichtigungen",
    apps: ["openmailer"],
    category: "communication",
    authType: "basic_auth",
    webhooks: true,
    rateLimitRPM: 100,
    requiredEnvVars: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN"],
    baseUrl: "https://api.twilio.com/2010-04-01",
    docsUrl: "https://www.twilio.com/docs/",
    icon: "twilio",
  },

  slack: {
    id: "slack",
    name: "Slack API",
    description: "Benachrichtigungen (Bounces, Kampagnen)",
    apps: ["openmailer"],
    category: "communication",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["SLACK_BOT_TOKEN"],
    optionalEnvVars: ["SLACK_SIGNING_SECRET"],
    baseUrl: "https://slack.com/api",
    docsUrl: "https://api.slack.com/",
    icon: "slack",
    oauthAuthUrl: "https://slack.com/oauth/v2/authorize",
    oauthTokenUrl: "https://slack.com/api/oauth.v2.access",
  },

  microsoft_graph: {
    id: "microsoft_graph",
    name: "Microsoft Graph",
    description: "Outlook/Exchange-Integration",
    apps: ["openmailer"],
    category: "communication",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 120,
    requiredEnvVars: ["MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET", "MICROSOFT_TENANT_ID"],
    baseUrl: "https://graph.microsoft.com/v1.0",
    docsUrl: "https://learn.microsoft.com/en-us/graph/",
    icon: "microsoft",
    oauthAuthUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    oauthTokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
    oauthScopes: ["Mail.ReadWrite", "Mail.Send"],
  },

  // ==================== OpenSEM (48-63) ====================

  google_search_console: {
    id: "google_search_console",
    name: "Google Search Console",
    description: "Suchdaten, Indexierung, Sitemaps",
    apps: ["opensem"],
    category: "seo",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    baseUrl: "https://searchconsole.googleapis.com/v1",
    docsUrl: "https://developers.google.com/webmaster-tools/v1/api_reference_index",
    icon: "google",
    oauthAuthUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    oauthTokenUrl: "https://oauth2.googleapis.com/token",
    oauthScopes: ["https://www.googleapis.com/auth/webmasters.readonly"],
  },

  google_analytics: {
    id: "google_analytics",
    name: "Google Analytics 4 (GA4)",
    description: "Traffic-Daten, Conversion-Tracking",
    apps: ["opensem"],
    category: "analytics",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    baseUrl: "https://analyticsdata.googleapis.com/v1beta",
    docsUrl: "https://developers.google.com/analytics/devguides/reporting/data/v1",
    icon: "google_analytics",
    oauthAuthUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    oauthTokenUrl: "https://oauth2.googleapis.com/token",
    oauthScopes: ["https://www.googleapis.com/auth/analytics.readonly"],
  },

  google_pagespeed: {
    id: "google_pagespeed",
    name: "Google PageSpeed Insights",
    description: "Core Web Vitals",
    apps: ["opensem"],
    category: "seo",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["GOOGLE_PAGESPEED_API_KEY"],
    baseUrl: "https://www.googleapis.com/pagespeedonline/v5",
    docsUrl: "https://developers.google.com/speed/docs/insights/v5/get-started",
    icon: "google",
  },

  semrush: {
    id: "semrush",
    name: "Semrush API",
    description: "Domain-Analyse, Keywords, Traffic",
    apps: ["opensem"],
    category: "seo",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["SEMRUSH_API_KEY"],
    baseUrl: "https://api.semrush.com",
    docsUrl: "https://developer.semrush.com/api/",
    icon: "semrush",
  },

  ahrefs: {
    id: "ahrefs",
    name: "Ahrefs API",
    description: "Backlink-Analyse, Keyword-Daten",
    apps: ["opensem"],
    category: "seo",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["AHREFS_API_TOKEN"],
    baseUrl: "https://api.ahrefs.com/v3",
    docsUrl: "https://ahrefs.com/api/documentation",
    icon: "ahrefs",
  },

  moz: {
    id: "moz",
    name: "Moz API",
    description: "Domain Authority, Link-Analyse",
    apps: ["opensem"],
    category: "seo",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["MOZ_ACCESS_ID", "MOZ_SECRET_KEY"],
    baseUrl: "https://lsapi.seomoz.com/v2",
    docsUrl: "https://moz.com/help/links-api",
    icon: "moz",
  },

  bing_webmaster: {
    id: "bing_webmaster",
    name: "Bing Webmaster Tools",
    description: "Bing-Suchdaten",
    apps: ["opensem"],
    category: "seo",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["BING_WEBMASTER_API_KEY"],
    baseUrl: "https://ssl.bing.com/webmaster/api.svc/json",
    docsUrl: "https://learn.microsoft.com/en-us/bingwebmaster/",
    icon: "bing",
  },

  screaming_frog: {
    id: "screaming_frog",
    name: "Screaming Frog API",
    description: "Technisches SEO-Crawling",
    apps: ["opensem"],
    category: "seo",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: ["SCREAMING_FROG_LICENSE_KEY"],
    baseUrl: "https://api.screamingfrog.co.uk",
    docsUrl: "https://www.screamingfrog.co.uk/seo-spider/user-guide/",
    icon: "screaming_frog",
  },

  sistrix: {
    id: "sistrix",
    name: "Sistrix API",
    description: "Sichtbarkeitsindex (DE-Markt)",
    apps: ["opensem"],
    category: "seo",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["SISTRIX_API_KEY"],
    baseUrl: "https://api.sistrix.com",
    docsUrl: "https://www.sistrix.com/api/",
    icon: "sistrix",
  },

  google_trends: {
    id: "google_trends",
    name: "Google Trends",
    description: "Keyword-Trend-Analyse",
    apps: ["opensem"],
    category: "seo",
    authType: "none",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: [],
    baseUrl: "https://trends.google.com",
    docsUrl: "https://trends.google.com/trends/",
    icon: "google",
  },

  google_my_business: {
    id: "google_my_business",
    name: "Google My Business",
    description: "Local SEO",
    apps: ["opensem"],
    category: "seo",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    baseUrl: "https://mybusinessbusinessinformation.googleapis.com/v1",
    docsUrl: "https://developers.google.com/my-business/",
    icon: "google",
    oauthAuthUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    oauthTokenUrl: "https://oauth2.googleapis.com/token",
  },

  schema_org: {
    id: "schema_org",
    name: "Schema.org Validator",
    description: "Structured-Data-Validierung",
    apps: ["opensem"],
    category: "seo",
    authType: "none",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: [],
    baseUrl: "https://validator.schema.org",
    docsUrl: "https://schema.org/docs/",
    icon: "schema_org",
  },

  majestic: {
    id: "majestic",
    name: "Majestic API",
    description: "Backlink-Datenbank",
    apps: ["opensem"],
    category: "seo",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["MAJESTIC_API_KEY"],
    baseUrl: "https://api.majestic.com/api/json",
    docsUrl: "https://developer-support.majestic.com/",
    icon: "majestic",
  },

  google_indexing: {
    id: "google_indexing",
    name: "Google Indexing API",
    description: "Schnelle Indexierung",
    apps: ["opensem"],
    category: "seo",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 200,
    requiredEnvVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    baseUrl: "https://indexing.googleapis.com/v3",
    docsUrl: "https://developers.google.com/search/apis/indexing-api/v3/quickstart",
    icon: "google",
    oauthTokenUrl: "https://oauth2.googleapis.com/token",
  },

  similarweb: {
    id: "similarweb",
    name: "SimilarWeb",
    description: "Traffic-Analyse, Wettbewerber",
    apps: ["opensem"],
    category: "analytics",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: ["SIMILARWEB_API_KEY"],
    baseUrl: "https://api.similarweb.com/v1",
    docsUrl: "https://developers.similarweb.com/docs",
    icon: "similarweb",
  },

  // ==================== OpenLawyer (64-75) ====================

  docusign: {
    id: "docusign",
    name: "DocuSign",
    description: "Digitale Unterschriften",
    apps: ["openlawyer"],
    category: "esignature",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["DOCUSIGN_INTEGRATION_KEY", "DOCUSIGN_SECRET_KEY"],
    baseUrl: "https://eu.docusign.net/restapi/v2.1",
    docsUrl: "https://developers.docusign.com/docs/esign-rest-api/",
    icon: "docusign",
    oauthAuthUrl: "https://account.docusign.com/oauth/auth",
    oauthTokenUrl: "https://account.docusign.com/oauth/token",
    oauthScopes: ["signature", "impersonation"],
  },

  adobe_sign: {
    id: "adobe_sign",
    name: "Adobe Sign",
    description: "Digitale Unterschriften",
    apps: ["openlawyer"],
    category: "esignature",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["ADOBE_SIGN_CLIENT_ID", "ADOBE_SIGN_CLIENT_SECRET"],
    baseUrl: "https://api.eu1.adobesign.com/api/rest/v6",
    docsUrl: "https://secure.eu1.adobesign.com/public/docs/restapi/v6",
    icon: "adobe",
    oauthAuthUrl: "https://secure.eu1.adobesign.com/public/oauth/v2",
    oauthTokenUrl: "https://api.eu1.adobesign.com/oauth/v2/token",
  },

  eurlex: {
    id: "eurlex",
    name: "EUR-Lex API",
    description: "EU-Rechtsvorschriften-Monitor",
    apps: ["openlawyer"],
    category: "legal",
    authType: "none",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: [],
    baseUrl: "https://eur-lex.europa.eu/eurlex-ws/rest",
    docsUrl: "https://eur-lex.europa.eu/content/tools/webservices/SearchWebServiceUserManual_v2.00.pdf",
    icon: "eu",
  },

  gesetze_im_internet: {
    id: "gesetze_im_internet",
    name: "Gesetze-im-Internet",
    description: "Deutsche Gesetze abrufen",
    apps: ["openlawyer"],
    category: "legal",
    authType: "none",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: [],
    baseUrl: "https://www.gesetze-im-internet.de",
    docsUrl: "https://www.gesetze-im-internet.de/",
    icon: "germany",
  },

  handelsregister: {
    id: "handelsregister",
    name: "Handelsregister",
    description: "HRB/HRA-Abfragen",
    apps: ["openlawyer"],
    category: "legal",
    authType: "custom",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: ["HANDELSREGISTER_USERNAME", "HANDELSREGISTER_PASSWORD"],
    baseUrl: "https://www.handelsregister.de",
    docsUrl: "https://www.handelsregister.de/",
    icon: "germany",
  },

  gdpr_register: {
    id: "gdpr_register",
    name: "GDPR Register API",
    description: "DSGVO-Verarbeitungsverzeichnis",
    apps: ["openlawyer"],
    category: "compliance",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["GDPR_REGISTER_API_KEY"],
    baseUrl: "https://api.gdprregister.eu/v1",
    docsUrl: "https://gdprregister.eu/",
    icon: "gdpr",
  },

  ejustice: {
    id: "ejustice",
    name: "eJustice Portal",
    description: "EU-Unternehmensregister",
    apps: ["openlawyer"],
    category: "legal",
    authType: "none",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: [],
    baseUrl: "https://e-justice.europa.eu",
    docsUrl: "https://e-justice.europa.eu/",
    icon: "eu",
  },

  consentmanager: {
    id: "consentmanager",
    name: "Consentmanager",
    description: "Cookie-Consent-Management",
    apps: ["openlawyer"],
    category: "compliance",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["CONSENTMANAGER_API_KEY"],
    baseUrl: "https://api.consentmanager.net/v1",
    docsUrl: "https://www.consentmanager.net/knowledge/api/",
    icon: "consentmanager",
  },

  cookiebot: {
    id: "cookiebot",
    name: "Cookiebot",
    description: "Cookie-Compliance-Scan",
    apps: ["openlawyer"],
    category: "compliance",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: ["COOKIEBOT_API_KEY", "COOKIEBOT_DOMAIN_GROUP_ID"],
    baseUrl: "https://manage.cookiebot.com/api/v1",
    docsUrl: "https://www.cookiebot.com/en/developer/",
    icon: "cookiebot",
  },

  google_safe_browsing: {
    id: "google_safe_browsing",
    name: "Google Safe Browsing",
    description: "Website-Sicherheitscheck",
    apps: ["openlawyer"],
    category: "compliance",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["GOOGLE_SAFE_BROWSING_API_KEY"],
    baseUrl: "https://safebrowsing.googleapis.com/v4",
    docsUrl: "https://developers.google.com/safe-browsing/v4/",
    icon: "google",
  },

  ssl_labs: {
    id: "ssl_labs",
    name: "SSL Labs API",
    description: "SSL-Zertifikat-Prüfung",
    apps: ["openlawyer"],
    category: "compliance",
    authType: "none",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: [],
    baseUrl: "https://api.ssllabs.com/api/v3",
    docsUrl: "https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md",
    icon: "ssl",
  },

  // ==================== OpenInventory: Shipping (76-80) ====================

  dhl: {
    id: "dhl",
    name: "DHL Business API",
    description: "Versandetiketten, Tracking",
    apps: ["openinventory"],
    category: "shipping",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 250,
    requiredEnvVars: ["DHL_API_KEY", "DHL_API_SECRET"],
    optionalEnvVars: ["DHL_ACCOUNT_NUMBER"],
    baseUrl: "https://api-eu.dhl.com",
    docsUrl: "https://developer.dhl.com/",
    icon: "dhl",
  },

  dpd: {
    id: "dpd",
    name: "DPD API",
    description: "Versand + Tracking",
    apps: ["openinventory"],
    category: "shipping",
    authType: "basic_auth",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["DPD_USERNAME", "DPD_PASSWORD", "DPD_DELIS_ID"],
    baseUrl: "https://public-ws.dpd.com/services",
    docsUrl: "https://esolutions.dpd.com/",
    icon: "dpd",
  },

  ups: {
    id: "ups",
    name: "UPS API",
    description: "Internationaler Versand",
    apps: ["openinventory"],
    category: "shipping",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["UPS_CLIENT_ID", "UPS_CLIENT_SECRET"],
    baseUrl: "https://onlinetools.ups.com/api",
    docsUrl: "https://developer.ups.com/",
    icon: "ups",
    oauthTokenUrl: "https://onlinetools.ups.com/security/v1/oauth/token",
  },

  fedex: {
    id: "fedex",
    name: "FedEx API",
    description: "Internationaler Versand",
    apps: ["openinventory"],
    category: "shipping",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["FEDEX_CLIENT_ID", "FEDEX_CLIENT_SECRET"],
    baseUrl: "https://apis.fedex.com",
    docsUrl: "https://developer.fedex.com/",
    icon: "fedex",
    oauthTokenUrl: "https://apis.fedex.com/oauth/token",
  },

  gls: {
    id: "gls",
    name: "GLS API",
    description: "Versand (EU)",
    apps: ["openinventory"],
    category: "shipping",
    authType: "basic_auth",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["GLS_USERNAME", "GLS_PASSWORD", "GLS_CONTACT_ID"],
    baseUrl: "https://api.gls-group.eu/public/v1",
    docsUrl: "https://api.gls-group.eu/",
    icon: "gls",
  },

  // ==================== OpenInventory: Marketplace & E-Commerce (81-88) ====================

  amazon_sp: {
    id: "amazon_sp",
    name: "Amazon SP-API",
    description: "Marketplace-Bestandssync",
    apps: ["openinventory"],
    category: "marketplace",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 30,
    requiredEnvVars: ["AMAZON_SP_CLIENT_ID", "AMAZON_SP_CLIENT_SECRET", "AMAZON_SP_REFRESH_TOKEN"],
    baseUrl: "https://sellingpartnerapi-eu.amazon.com",
    docsUrl: "https://developer-docs.amazon.com/sp-api/",
    icon: "amazon",
    oauthTokenUrl: "https://api.amazon.com/auth/o2/token",
  },

  ebay: {
    id: "ebay",
    name: "eBay API",
    description: "Marketplace-Bestandssync",
    apps: ["openinventory"],
    category: "marketplace",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["EBAY_CLIENT_ID", "EBAY_CLIENT_SECRET"],
    baseUrl: "https://api.ebay.com",
    docsUrl: "https://developer.ebay.com/docs",
    icon: "ebay",
    oauthAuthUrl: "https://auth.ebay.com/oauth2/authorize",
    oauthTokenUrl: "https://api.ebay.com/identity/v1/oauth2/token",
  },

  shopify: {
    id: "shopify",
    name: "Shopify API",
    description: "E-Commerce-Bestandssync",
    apps: ["openinventory"],
    category: "ecommerce",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 40,
    requiredEnvVars: ["SHOPIFY_SHOP_DOMAIN", "SHOPIFY_ACCESS_TOKEN"],
    baseUrl: "https://{shop}.myshopify.com/admin/api/2024-01",
    docsUrl: "https://shopify.dev/docs/api",
    icon: "shopify",
  },

  woocommerce: {
    id: "woocommerce",
    name: "WooCommerce API",
    description: "E-Commerce-Bestandssync",
    apps: ["openinventory"],
    category: "ecommerce",
    authType: "basic_auth",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["WOOCOMMERCE_URL", "WOOCOMMERCE_CONSUMER_KEY", "WOOCOMMERCE_CONSUMER_SECRET"],
    baseUrl: "https://example.com/wp-json/wc/v3",
    docsUrl: "https://woocommerce.github.io/woocommerce-rest-api-docs/",
    icon: "woocommerce",
  },

  jtl: {
    id: "jtl",
    name: "JTL API",
    description: "Warenwirtschaft-Sync",
    apps: ["openinventory"],
    category: "ecommerce",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["JTL_API_KEY", "JTL_URL"],
    baseUrl: "https://api.jtl-software.com/v1",
    docsUrl: "https://guide.jtl-software.de/",
    icon: "jtl",
  },

  afterbuy: {
    id: "afterbuy",
    name: "Afterbuy API",
    description: "Multi-Channel-Sync",
    apps: ["openinventory"],
    category: "ecommerce",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["AFTERBUY_PARTNER_ID", "AFTERBUY_ACCOUNT_TOKEN"],
    baseUrl: "https://api.afterbuy.de/afterbuy/ABInterface.aspx",
    docsUrl: "https://xmldoku.afterbuy.de/",
    icon: "afterbuy",
  },

  gs1_ean: {
    id: "gs1_ean",
    name: "EAN/GTIN API (GS1)",
    description: "Barcode-Validierung",
    apps: ["openinventory"],
    category: "ecommerce",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["GS1_API_KEY"],
    baseUrl: "https://api.gs1.org/v1",
    docsUrl: "https://www.gs1.org/services/verified-by-gs1",
    icon: "gs1",
  },

  billbee: {
    id: "billbee",
    name: "Billbee API",
    description: "Multichannel-Order-Management",
    apps: ["openinventory"],
    category: "ecommerce",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["BILLBEE_API_KEY", "BILLBEE_USERNAME", "BILLBEE_PASSWORD"],
    baseUrl: "https://api.billbee.io/api/v1",
    docsUrl: "https://api.billbee.io/swagger/ui/index",
    icon: "billbee",
  },

  // ==================== OpenPayroll (89-95) ====================

  elster_payroll: {
    id: "elster_payroll",
    name: "ELSTER (Lohnsteuer)",
    description: "Lohnsteueranmeldung",
    apps: ["openpayroll"],
    category: "payroll",
    authType: "custom",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: ["ELSTER_CERTIFICATE_PATH", "ELSTER_CERTIFICATE_PIN"],
    baseUrl: "https://www.elster.de/elsterweb/softwarehersteller",
    docsUrl: "https://www.elster.de/elsterweb/entwickler",
    icon: "elster",
  },

  sv_meldeportal: {
    id: "sv_meldeportal",
    name: "SV-Meldeportal",
    description: "Sozialversicherungsmeldungen",
    apps: ["openpayroll"],
    category: "payroll",
    authType: "custom",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: ["SV_MELDE_BETRIEBSNUMMER", "SV_MELDE_CERTIFICATE"],
    baseUrl: "https://www.sv-meldeportal.de",
    docsUrl: "https://www.gkv-datenaustausch.de/",
    icon: "sv",
  },

  itsg_gkv: {
    id: "itsg_gkv",
    name: "ITSG (GKV)",
    description: "Krankenkassen-Datenaustausch",
    apps: ["openpayroll"],
    category: "payroll",
    authType: "custom",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: ["ITSG_BETRIEBSNUMMER", "ITSG_CERTIFICATE"],
    baseUrl: "https://www.itsg.de",
    docsUrl: "https://www.gkv-datenaustausch.de/",
    icon: "itsg",
  },

  deutsche_rentenversicherung: {
    id: "deutsche_rentenversicherung",
    name: "Deutsche Rentenversicherung",
    description: "RV-Meldungen",
    apps: ["openpayroll"],
    category: "payroll",
    authType: "custom",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: ["DRV_BETRIEBSNUMMER", "DRV_CERTIFICATE"],
    baseUrl: "https://www.deutsche-rentenversicherung.de",
    docsUrl: "https://www.deutsche-rentenversicherung.de/",
    icon: "drv",
  },

  personio: {
    id: "personio",
    name: "Personio API",
    description: "HR-System-Sync",
    apps: ["openpayroll"],
    category: "hr",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 200,
    requiredEnvVars: ["PERSONIO_CLIENT_ID", "PERSONIO_CLIENT_SECRET"],
    baseUrl: "https://api.personio.de/v1",
    docsUrl: "https://developer.personio.de/reference",
    icon: "personio",
  },

  bamboohr: {
    id: "bamboohr",
    name: "BambooHR API",
    description: "HR-System-Sync",
    apps: ["openpayroll"],
    category: "hr",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["BAMBOOHR_API_KEY", "BAMBOOHR_SUBDOMAIN"],
    baseUrl: "https://api.bamboohr.com/api/gateway.php",
    docsUrl: "https://documentation.bamboohr.com/reference",
    icon: "bamboohr",
  },

  hrworks: {
    id: "hrworks",
    name: "HRworks API",
    description: "HR-System-Sync (DE)",
    apps: ["openpayroll"],
    category: "hr",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["HRWORKS_ACCESS_KEY", "HRWORKS_SECRET_KEY"],
    baseUrl: "https://api.hrworks.de/v2",
    docsUrl: "https://developers.hrworks.de/",
    icon: "hrworks",
  },

  // ==================== OpenFlow (96-100) ====================

  salesforce: {
    id: "salesforce",
    name: "Salesforce API",
    description: "Form-Submissions → CRM",
    apps: ["openflow"],
    category: "crm",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 100,
    requiredEnvVars: ["SALESFORCE_CLIENT_ID", "SALESFORCE_CLIENT_SECRET"],
    baseUrl: "https://login.salesforce.com/services/data/v59.0",
    docsUrl: "https://developer.salesforce.com/docs/apis",
    icon: "salesforce",
    oauthAuthUrl: "https://login.salesforce.com/services/oauth2/authorize",
    oauthTokenUrl: "https://login.salesforce.com/services/oauth2/token",
  },

  zapier: {
    id: "zapier",
    name: "Zapier Webhooks",
    description: "No-Code-Automationen",
    apps: ["openflow"],
    category: "automation",
    authType: "none",
    webhooks: true,
    rateLimitRPM: 100,
    requiredEnvVars: ["ZAPIER_WEBHOOK_URL"],
    baseUrl: "https://hooks.zapier.com",
    docsUrl: "https://zapier.com/developer/documentation/v2/",
    icon: "zapier",
  },

  make: {
    id: "make",
    name: "Make (Integromat)",
    description: "No-Code-Automationen",
    apps: ["openflow"],
    category: "automation",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["MAKE_API_TOKEN"],
    baseUrl: "https://eu1.make.com/api/v2",
    docsUrl: "https://www.make.com/en/api-documentation",
    icon: "make",
  },

  google_sheets: {
    id: "google_sheets",
    name: "Google Sheets API",
    description: "Submissions → Tabelle",
    apps: ["openflow"],
    category: "productivity",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    baseUrl: "https://sheets.googleapis.com/v4",
    docsUrl: "https://developers.google.com/sheets/api",
    icon: "google_sheets",
    oauthAuthUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    oauthTokenUrl: "https://oauth2.googleapis.com/token",
    oauthScopes: ["https://www.googleapis.com/auth/spreadsheets"],
  },

  notion: {
    id: "notion",
    name: "Notion API",
    description: "Submissions → Datenbank",
    apps: ["openflow"],
    category: "productivity",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 3,
    requiredEnvVars: ["NOTION_CLIENT_ID", "NOTION_CLIENT_SECRET"],
    baseUrl: "https://api.notion.com/v1",
    docsUrl: "https://developers.notion.com/",
    icon: "notion",
    oauthAuthUrl: "https://api.notion.com/v1/oauth/authorize",
    oauthTokenUrl: "https://api.notion.com/v1/oauth/token",
  },
  // ==================== OpenAccounting: Additional 50 APIs (33-82) ====================

  // --- Payment Processors (Additional) ---

  adyen: {
    id: "adyen",
    name: "Adyen",
    description: "Enterprise-Zahlungsplattform, Multi-Channel",
    apps: ["openaccounting"],
    category: "payment",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 100,
    requiredEnvVars: ["ADYEN_API_KEY", "ADYEN_MERCHANT_ACCOUNT"],
    baseUrl: "https://checkout-test.adyen.com/v71",
    docsUrl: "https://docs.adyen.com/api-explorer/",
    icon: "adyen",
  },

  unzer: {
    id: "unzer",
    name: "Unzer (Heidelpay)",
    description: "Zahlungsabwicklung für DACH-Markt",
    apps: ["openaccounting"],
    category: "payment",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["UNZER_PRIVATE_KEY"],
    baseUrl: "https://api.unzer.com/v1",
    docsUrl: "https://docs.unzer.com/",
    icon: "unzer",
  },

  payone: {
    id: "payone",
    name: "PAYONE",
    description: "Payment Service Provider (DE)",
    apps: ["openaccounting"],
    category: "payment",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["PAYONE_MERCHANT_ID", "PAYONE_PORTAL_ID", "PAYONE_KEY"],
    baseUrl: "https://api.pay1.de/v1",
    docsUrl: "https://docs.payone.com/",
    icon: "payone",
  },

  giropay: {
    id: "giropay",
    name: "giropay / paydirekt",
    description: "Deutsche Online-Überweisung",
    apps: ["openaccounting"],
    category: "payment",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 30,
    requiredEnvVars: ["GIROPAY_MERCHANT_ID", "GIROPAY_PROJECT_ID", "GIROPAY_SECRET"],
    baseUrl: "https://payment.giropay.de/api/v2",
    docsUrl: "https://www.giropay.de/haendler/api-dokumentation/",
    icon: "giropay",
  },

  ratepay: {
    id: "ratepay",
    name: "Ratepay",
    description: "Ratenzahlung, Rechnungskauf (B2C/B2B)",
    apps: ["openaccounting"],
    category: "payment",
    authType: "basic_auth",
    webhooks: true,
    rateLimitRPM: 30,
    requiredEnvVars: ["RATEPAY_PROFILE_ID", "RATEPAY_SECURITY_CODE"],
    baseUrl: "https://gateway.ratepay.com/api/xml/1_0",
    docsUrl: "https://docs.ratepay.com/",
    icon: "ratepay",
  },

  // --- Banking (Additional) ---

  ing_api: {
    id: "ing_api",
    name: "ING Open Banking",
    description: "ING PSD2 Banking-Integration",
    apps: ["openaccounting"],
    category: "banking",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["ING_CLIENT_ID", "ING_CLIENT_SECRET", "ING_CERTIFICATE"],
    baseUrl: "https://api.ing.com",
    docsUrl: "https://developer.ing.com/",
    icon: "ing",
    oauthTokenUrl: "https://api.ing.com/oauth2/token",
  },

  postbank_api: {
    id: "postbank_api",
    name: "Postbank API",
    description: "Postbank PSD2 Banking",
    apps: ["openaccounting"],
    category: "banking",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["POSTBANK_CLIENT_ID", "POSTBANK_CLIENT_SECRET"],
    baseUrl: "https://xs2a-api.postbank.de/v1",
    docsUrl: "https://developer.postbank.de/",
    icon: "postbank",
    oauthTokenUrl: "https://xs2a-api.postbank.de/v1/oauth/token",
  },

  revolut_business: {
    id: "revolut_business",
    name: "Revolut Business",
    description: "Geschäftskonto, Zahlungen, FX",
    apps: ["openaccounting"],
    category: "banking",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 120,
    requiredEnvVars: ["REVOLUT_CLIENT_ID", "REVOLUT_PRIVATE_KEY"],
    baseUrl: "https://b2b.revolut.com/api/1.0",
    docsUrl: "https://developer.revolut.com/docs/business/",
    icon: "revolut",
    oauthTokenUrl: "https://b2b.revolut.com/api/1.0/auth/token",
  },

  qonto: {
    id: "qonto",
    name: "Qonto",
    description: "Geschäftskonto für KMU (EU)",
    apps: ["openaccounting"],
    category: "banking",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["QONTO_ORGANIZATION_SLUG", "QONTO_SECRET_KEY"],
    baseUrl: "https://thirdparty.qonto.com/v2",
    docsUrl: "https://api-doc.qonto.com/",
    icon: "qonto",
  },

  figo: {
    id: "figo",
    name: "figo / finAPI",
    description: "Multi-Bank-Aggregation (PSD2)",
    apps: ["openaccounting"],
    category: "banking",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["FINAPI_CLIENT_ID", "FINAPI_CLIENT_SECRET"],
    baseUrl: "https://live.finapi.io/api/v2",
    docsUrl: "https://documentation.finapi.io/",
    icon: "finapi",
    oauthTokenUrl: "https://live.finapi.io/api/v2/oauth/token",
  },

  kontist: {
    id: "kontist",
    name: "Kontist",
    description: "Banking für Freelancer/Selbstständige",
    apps: ["openaccounting"],
    category: "banking",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["KONTIST_CLIENT_ID", "KONTIST_CLIENT_SECRET"],
    baseUrl: "https://api.kontist.com/api",
    docsUrl: "https://kontist.com/developer/",
    icon: "kontist",
    oauthTokenUrl: "https://api.kontist.com/api/oauth/token",
  },

  // --- Tax, Compliance & E-Invoicing (Additional) ---

  taxfix_api: {
    id: "taxfix_api",
    name: "Taxfix API",
    description: "Steuererklärungs-Datenimport",
    apps: ["openaccounting"],
    category: "tax",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["TAXFIX_API_KEY"],
    baseUrl: "https://api.taxfix.de/v1",
    docsUrl: "https://taxfix.de/partner",
    icon: "taxfix",
  },

  buhl_data: {
    id: "buhl_data",
    name: "Buhl Data (WISO)",
    description: "WISO Steuersoftware Datenaustausch",
    apps: ["openaccounting"],
    category: "tax",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["BUHL_API_KEY"],
    baseUrl: "https://api.buhl.de/v1",
    docsUrl: "https://www.buhl.de/",
    icon: "buhl",
  },

  vatify: {
    id: "vatify",
    name: "Vatify.eu",
    description: "Erweiterte EU-USt-Validierung + Monitoring",
    apps: ["openaccounting"],
    category: "tax",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 120,
    requiredEnvVars: ["VATIFY_API_KEY"],
    baseUrl: "https://api.vatify.eu/v1",
    docsUrl: "https://vatify.eu/docs",
    icon: "vatify",
  },

  facturx: {
    id: "facturx",
    name: "Factur-X (FR/EU)",
    description: "Französischer E-Invoicing-Standard",
    apps: ["openaccounting"],
    category: "invoicing",
    authType: "none",
    webhooks: false,
    rateLimitRPM: 1000,
    requiredEnvVars: [],
    baseUrl: "https://www.factur-x.org",
    docsUrl: "https://www.factur-x.org/en/",
    icon: "facturx",
  },

  chorus_pro: {
    id: "chorus_pro",
    name: "Chorus Pro (FR)",
    description: "Französisches E-Invoicing-Portal (öffentlich)",
    apps: ["openaccounting"],
    category: "invoicing",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 30,
    requiredEnvVars: ["CHORUS_PRO_CLIENT_ID", "CHORUS_PRO_CLIENT_SECRET"],
    baseUrl: "https://chorus-pro.gouv.fr/cpro/api/v1",
    docsUrl: "https://communaute.chorus-pro.gouv.fr/",
    icon: "chorus_pro",
    oauthTokenUrl: "https://chorus-pro.gouv.fr/cpro/api/oauth/token",
  },

  sdi_italy: {
    id: "sdi_italy",
    name: "SDI (FatturaPA, IT)",
    description: "Italienisches E-Invoicing via SDI",
    apps: ["openaccounting"],
    category: "invoicing",
    authType: "custom",
    webhooks: true,
    rateLimitRPM: 30,
    requiredEnvVars: ["SDI_CODICE_DESTINATARIO", "SDI_CERTIFICATE"],
    baseUrl: "https://ivaservizi.agenziaentrate.gov.it/ser/s/v1",
    docsUrl: "https://www.fatturapa.gov.it/",
    icon: "sdi",
  },

  // --- ERP & Accounting Tools (Additional) ---

  bexio: {
    id: "bexio",
    name: "bexio",
    description: "Schweizer Buchhaltungssoftware",
    apps: ["openaccounting"],
    category: "erp",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["BEXIO_CLIENT_ID", "BEXIO_CLIENT_SECRET"],
    baseUrl: "https://api.bexio.com/2.0",
    docsUrl: "https://docs.bexio.com/",
    icon: "bexio",
    oauthAuthUrl: "https://idp.bexio.com/authorize",
    oauthTokenUrl: "https://idp.bexio.com/token",
  },

  xero: {
    id: "xero",
    name: "Xero",
    description: "Cloud-Buchhaltung (international)",
    apps: ["openaccounting"],
    category: "erp",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["XERO_CLIENT_ID", "XERO_CLIENT_SECRET"],
    baseUrl: "https://api.xero.com/api.xro/2.0",
    docsUrl: "https://developer.xero.com/documentation/",
    icon: "xero",
    oauthAuthUrl: "https://login.xero.com/identity/connect/authorize",
    oauthTokenUrl: "https://identity.xero.com/connect/token",
    oauthScopes: ["openid", "profile", "email", "accounting.transactions", "accounting.contacts"],
  },

  quickbooks: {
    id: "quickbooks",
    name: "QuickBooks Online",
    description: "Intuit Cloud-Buchhaltung",
    apps: ["openaccounting"],
    category: "erp",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 500,
    requiredEnvVars: ["QUICKBOOKS_CLIENT_ID", "QUICKBOOKS_CLIENT_SECRET"],
    baseUrl: "https://quickbooks.api.intuit.com/v3",
    docsUrl: "https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/account",
    icon: "quickbooks",
    oauthAuthUrl: "https://appcenter.intuit.com/connect/oauth2",
    oauthTokenUrl: "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
  },

  freshbooks: {
    id: "freshbooks",
    name: "FreshBooks",
    description: "Rechnungs- und Buchhaltungstool",
    apps: ["openaccounting"],
    category: "erp",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["FRESHBOOKS_CLIENT_ID", "FRESHBOOKS_CLIENT_SECRET"],
    baseUrl: "https://api.freshbooks.com/accounting/account",
    docsUrl: "https://www.freshbooks.com/api/",
    icon: "freshbooks",
    oauthAuthUrl: "https://auth.freshbooks.com/oauth/authorize",
    oauthTokenUrl: "https://api.freshbooks.com/auth/oauth/token",
  },

  sage: {
    id: "sage",
    name: "Sage Business Cloud",
    description: "Sage Buchhaltung (DE/EU)",
    apps: ["openaccounting"],
    category: "erp",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["SAGE_CLIENT_ID", "SAGE_CLIENT_SECRET"],
    baseUrl: "https://api.accounting.sage.com/v3.1",
    docsUrl: "https://developer.sage.com/accounting/",
    icon: "sage",
    oauthAuthUrl: "https://www.sageone.com/oauth2/auth/central",
    oauthTokenUrl: "https://oauth.accounting.sage.com/token",
  },

  zoho_books: {
    id: "zoho_books",
    name: "Zoho Books",
    description: "Cloud-Buchhaltung + Steuern",
    apps: ["openaccounting"],
    category: "erp",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 100,
    requiredEnvVars: ["ZOHO_CLIENT_ID", "ZOHO_CLIENT_SECRET"],
    baseUrl: "https://www.zohoapis.eu/books/v3",
    docsUrl: "https://www.zoho.com/books/api/v3/",
    icon: "zoho",
    oauthAuthUrl: "https://accounts.zoho.eu/oauth/v2/auth",
    oauthTokenUrl: "https://accounts.zoho.eu/oauth/v2/token",
  },

  odoo: {
    id: "odoo",
    name: "Odoo ERP",
    description: "Open-Source ERP-Sync (Accounting-Modul)",
    apps: ["openaccounting"],
    category: "erp",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["ODOO_URL", "ODOO_DB", "ODOO_USERNAME", "ODOO_API_KEY"],
    baseUrl: "https://example.odoo.com/api/v1",
    docsUrl: "https://www.odoo.com/documentation/17.0/developer/",
    icon: "odoo",
  },

  scopevisio: {
    id: "scopevisio",
    name: "Scopevisio",
    description: "Cloud-ERP + FiBu (DE)",
    apps: ["openaccounting"],
    category: "erp",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["SCOPEVISIO_CLIENT_ID", "SCOPEVISIO_CLIENT_SECRET"],
    baseUrl: "https://appload.scopevisio.com/rest",
    docsUrl: "https://www.scopevisio.com/api/",
    icon: "scopevisio",
    oauthTokenUrl: "https://appload.scopevisio.com/rest/token",
  },

  papierkram: {
    id: "papierkram",
    name: "Papierkram",
    description: "Buchhaltung für Selbstständige (DE)",
    apps: ["openaccounting"],
    category: "erp",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["PAPIERKRAM_API_KEY", "PAPIERKRAM_SUBDOMAIN"],
    baseUrl: "https://example.papierkram.de/api/v1",
    docsUrl: "https://die-papierkram-api.de/",
    icon: "papierkram",
  },

  debitoor_sumup: {
    id: "debitoor_sumup",
    name: "Debitoor (SumUp)",
    description: "Rechnungserstellung für Freelancer",
    apps: ["openaccounting"],
    category: "erp",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["DEBITOOR_CLIENT_ID", "DEBITOOR_CLIENT_SECRET"],
    baseUrl: "https://api.debitoor.com/api/v1.0",
    docsUrl: "https://debitoor.com/api",
    icon: "debitoor",
    oauthTokenUrl: "https://app.debitoor.com/oauth/token",
  },

  collmex: {
    id: "collmex",
    name: "Collmex",
    description: "Kaufmännische Software (DE)",
    apps: ["openaccounting"],
    category: "erp",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["COLLMEX_CUSTOMER_ID", "COLLMEX_USERNAME", "COLLMEX_PASSWORD"],
    baseUrl: "https://www.collmex.de/cgi-bin/cgi.exe",
    docsUrl: "https://www.collmex.de/cgi-bin/cgi.exe?1005,1,help,api",
    icon: "collmex",
  },

  orgamax: {
    id: "orgamax",
    name: "orgaMAX",
    description: "Büroverwaltung + Buchhaltung (DE)",
    apps: ["openaccounting"],
    category: "erp",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["ORGAMAX_API_KEY"],
    baseUrl: "https://api.orgamax.de/v1",
    docsUrl: "https://www.orgamax.de/",
    icon: "orgamax",
  },

  // --- OCR & Document Processing (Additional) ---

  klippa: {
    id: "klippa",
    name: "Klippa OCR",
    description: "Beleg-/Rechnungs-OCR (EU, GDPR-konform)",
    apps: ["openaccounting"],
    category: "ocr",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["KLIPPA_API_KEY"],
    baseUrl: "https://custom-ocr.klippa.com/api/v1",
    docsUrl: "https://custom-ocr.klippa.com/docs",
    icon: "klippa",
  },

  mindee: {
    id: "mindee",
    name: "Mindee",
    description: "KI-Dokumentenextraktion (Rechnungen, Belege)",
    apps: ["openaccounting"],
    category: "ocr",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 30,
    requiredEnvVars: ["MINDEE_API_KEY"],
    baseUrl: "https://api.mindee.net/v1",
    docsUrl: "https://developers.mindee.com/docs/",
    icon: "mindee",
  },

  rossum: {
    id: "rossum",
    name: "Rossum",
    description: "KI-gestützte Rechnungsverarbeitung",
    apps: ["openaccounting"],
    category: "ocr",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 30,
    requiredEnvVars: ["ROSSUM_API_KEY"],
    baseUrl: "https://elis.rossum.ai/api/v1",
    docsUrl: "https://elis.rossum.ai/api/docs/",
    icon: "rossum",
  },

  veryfi: {
    id: "veryfi",
    name: "Veryfi",
    description: "Echtzeit-OCR für Belege, Rechnungen, Quittungen",
    apps: ["openaccounting"],
    category: "ocr",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["VERYFI_CLIENT_ID", "VERYFI_CLIENT_SECRET", "VERYFI_USERNAME", "VERYFI_API_KEY"],
    baseUrl: "https://api.veryfi.com/api/v8",
    docsUrl: "https://docs.veryfi.com/",
    icon: "veryfi",
  },

  // --- Expense Management ---

  spendesk: {
    id: "spendesk",
    name: "Spendesk",
    description: "Ausgabenmanagement + Firmenkarten",
    apps: ["openaccounting"],
    category: "payment",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["SPENDESK_CLIENT_ID", "SPENDESK_CLIENT_SECRET"],
    baseUrl: "https://api.spendesk.com/v3",
    docsUrl: "https://developers.spendesk.com/",
    icon: "spendesk",
    oauthTokenUrl: "https://api.spendesk.com/oauth/token",
  },

  pleo: {
    id: "pleo",
    name: "Pleo",
    description: "Firmenkarten + Ausgabenabrechnung",
    apps: ["openaccounting"],
    category: "payment",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["PLEO_CLIENT_ID", "PLEO_CLIENT_SECRET"],
    baseUrl: "https://external.pleo.io",
    docsUrl: "https://developers.pleo.io/",
    icon: "pleo",
    oauthTokenUrl: "https://auth.pleo.io/oauth/token",
  },

  moss: {
    id: "moss",
    name: "Moss (ex Vanta)",
    description: "Firmenkreditkarten + Rechnungsmanagement",
    apps: ["openaccounting"],
    category: "payment",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["MOSS_API_KEY"],
    baseUrl: "https://api.getmoss.com/v1",
    docsUrl: "https://developers.getmoss.com/",
    icon: "moss",
  },

  expensify: {
    id: "expensify",
    name: "Expensify",
    description: "Reisekostenabrechnung + Belegerfassung",
    apps: ["openaccounting"],
    category: "payment",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["EXPENSIFY_PARTNER_USER_ID", "EXPENSIFY_PARTNER_USER_SECRET"],
    baseUrl: "https://integrations.expensify.com/Integration-Server/ExpensifyIntegrations",
    docsUrl: "https://integrations.expensify.com/Integration-Server/doc/",
    icon: "expensify",
  },

  // --- Currency & Exchange Rates ---

  ecb_rates: {
    id: "ecb_rates",
    name: "EZB Wechselkurse",
    description: "Offizielle EZB-Referenzkurse (täglich)",
    apps: ["openaccounting"],
    category: "banking",
    authType: "none",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: [],
    baseUrl: "https://data-api.ecb.europa.eu/service/data/EXR",
    docsUrl: "https://data.ecb.europa.eu/help/api/overview",
    icon: "ecb",
  },

  open_exchange_rates: {
    id: "open_exchange_rates",
    name: "Open Exchange Rates",
    description: "Echtzeit-Wechselkurse (170+ Währungen)",
    apps: ["openaccounting"],
    category: "banking",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["OXR_APP_ID"],
    baseUrl: "https://openexchangerates.org/api",
    docsUrl: "https://docs.openexchangerates.org/",
    icon: "oxr",
  },

  currencycloud: {
    id: "currencycloud",
    name: "Currencycloud",
    description: "B2B FX-Zahlungen, Hedging",
    apps: ["openaccounting"],
    category: "banking",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["CURRENCYCLOUD_LOGIN_ID", "CURRENCYCLOUD_API_KEY"],
    baseUrl: "https://api.currencycloud.com/v2",
    docsUrl: "https://developer.currencycloud.com/",
    icon: "currencycloud",
  },

  // --- Credit & Risk ---

  creditreform: {
    id: "creditreform",
    name: "Creditreform",
    description: "Bonitätsprüfung, Firmenauskünfte (DE)",
    apps: ["openaccounting"],
    category: "tax",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["CREDITREFORM_API_KEY", "CREDITREFORM_CUSTOMER_ID"],
    baseUrl: "https://api.creditreform.de/v1",
    docsUrl: "https://www.creditreform.de/",
    icon: "creditreform",
  },

  schufa: {
    id: "schufa",
    name: "SCHUFA B2B",
    description: "Bonitätsauskünfte Geschäftskunden",
    apps: ["openaccounting"],
    category: "tax",
    authType: "custom",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: ["SCHUFA_PARTNER_ID", "SCHUFA_CERTIFICATE"],
    baseUrl: "https://gateway.schufa.de/api/v1",
    docsUrl: "https://www.schufa.de/lp/b2b/",
    icon: "schufa",
  },

  crif_buergel: {
    id: "crif_buergel",
    name: "CRIF Bürgel",
    description: "Wirtschaftsauskunft, Debitorenmanagement",
    apps: ["openaccounting"],
    category: "tax",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["CRIF_API_KEY", "CRIF_USERNAME"],
    baseUrl: "https://api.crifbuergel.de/v1",
    docsUrl: "https://www.crifbuergel.de/",
    icon: "crif",
  },

  // --- Payment Collection & Dunning ---

  creditshelf: {
    id: "creditshelf",
    name: "creditshelf",
    description: "Unternehmensfinanzierung, Factoring",
    apps: ["openaccounting"],
    category: "banking",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 30,
    requiredEnvVars: ["CREDITSHELF_API_KEY"],
    baseUrl: "https://api.creditshelf.com/v1",
    docsUrl: "https://www.creditshelf.com/",
    icon: "creditshelf",
  },

  bilendo: {
    id: "bilendo",
    name: "Bilendo",
    description: "Forderungsmanagement, Mahnwesen-Automatisierung",
    apps: ["openaccounting"],
    category: "invoicing",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["BILENDO_API_KEY"],
    baseUrl: "https://api.bilendo.de/v1",
    docsUrl: "https://www.bilendo.de/api",
    icon: "bilendo",
  },

  auxmoney: {
    id: "auxmoney",
    name: "auxmoney Business",
    description: "Unternehmenskredite, Forderungsverkauf",
    apps: ["openaccounting"],
    category: "banking",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 30,
    requiredEnvVars: ["AUXMONEY_API_KEY", "AUXMONEY_PARTNER_ID"],
    baseUrl: "https://api.auxmoney.com/v1",
    docsUrl: "https://www.auxmoney.com/",
    icon: "auxmoney",
  },

  // --- Time Tracking & Project Billing ---

  clockodo: {
    id: "clockodo",
    name: "Clockodo",
    description: "Zeiterfassung → Rechnungsstellung (DE)",
    apps: ["openaccounting"],
    category: "erp",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["CLOCKODO_EMAIL", "CLOCKODO_API_KEY"],
    baseUrl: "https://my.clockodo.com/api",
    docsUrl: "https://www.clockodo.com/de/api/",
    icon: "clockodo",
  },

  toggl_track: {
    id: "toggl_track",
    name: "Toggl Track",
    description: "Zeiterfassung für Rechnungslegung",
    apps: ["openaccounting"],
    category: "erp",
    authType: "api_key",
    webhooks: true,
    rateLimitRPM: 60,
    requiredEnvVars: ["TOGGL_API_TOKEN"],
    baseUrl: "https://api.track.toggl.com/api/v9",
    docsUrl: "https://engineering.toggl.com/docs/",
    icon: "toggl",
  },

  harvest: {
    id: "harvest",
    name: "Harvest",
    description: "Zeiterfassung + Rechnungsstellung",
    apps: ["openaccounting"],
    category: "erp",
    authType: "oauth2",
    webhooks: true,
    rateLimitRPM: 100,
    requiredEnvVars: ["HARVEST_CLIENT_ID", "HARVEST_CLIENT_SECRET"],
    baseUrl: "https://api.harvestapp.com/v2",
    docsUrl: "https://help.getharvest.com/api-v2/",
    icon: "harvest",
    oauthAuthUrl: "https://id.getharvest.com/oauth2/authorize",
    oauthTokenUrl: "https://id.getharvest.com/api/v2/oauth2/token",
  },

  // --- Reporting & BI ---

  google_bigquery: {
    id: "google_bigquery",
    name: "Google BigQuery",
    description: "Finanzdaten-Analyse, Reporting-Warehouse",
    apps: ["openaccounting"],
    category: "ai",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["GOOGLE_CLOUD_PROJECT_ID", "GOOGLE_CLOUD_CREDENTIALS"],
    baseUrl: "https://bigquery.googleapis.com/bigquery/v2",
    docsUrl: "https://cloud.google.com/bigquery/docs/reference/rest",
    icon: "google_cloud",
    oauthTokenUrl: "https://oauth2.googleapis.com/token",
  },

  tableau: {
    id: "tableau",
    name: "Tableau",
    description: "BI-Dashboard für Finanzdaten",
    apps: ["openaccounting"],
    category: "ai",
    authType: "api_key",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["TABLEAU_TOKEN_NAME", "TABLEAU_TOKEN_VALUE", "TABLEAU_SITE_ID"],
    baseUrl: "https://eu-west-1a.online.tableau.com/api/3.21",
    docsUrl: "https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api.htm",
    icon: "tableau",
  },

  power_bi: {
    id: "power_bi",
    name: "Microsoft Power BI",
    description: "BI-Dashboard + Finanzberichte",
    apps: ["openaccounting"],
    category: "ai",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["POWER_BI_CLIENT_ID", "POWER_BI_CLIENT_SECRET", "POWER_BI_TENANT_ID"],
    baseUrl: "https://api.powerbi.com/v1.0/myorg",
    docsUrl: "https://learn.microsoft.com/en-us/rest/api/power-bi/",
    icon: "microsoft",
    oauthTokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
  },

  // --- Miscellaneous Accounting ---

  amazon_business: {
    id: "amazon_business",
    name: "Amazon Business",
    description: "Geschäftseinkäufe, Rechnungsimport",
    apps: ["openaccounting"],
    category: "erp",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 30,
    requiredEnvVars: ["AMAZON_BIZ_CLIENT_ID", "AMAZON_BIZ_CLIENT_SECRET"],
    baseUrl: "https://business-api.amazon.de/api/v1",
    docsUrl: "https://developer.amazon.com/business",
    icon: "amazon",
    oauthTokenUrl: "https://api.amazon.com/auth/o2/token",
  },

  bundesanzeiger: {
    id: "bundesanzeiger",
    name: "Bundesanzeiger",
    description: "Jahresabschluss-Veröffentlichung (DE)",
    apps: ["openaccounting"],
    category: "tax",
    authType: "custom",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: ["BUNDESANZEIGER_USERNAME", "BUNDESANZEIGER_PASSWORD"],
    baseUrl: "https://www.bundesanzeiger.de",
    docsUrl: "https://www.bundesanzeiger.de/",
    icon: "bundesanzeiger",
  },

  unternehmensregister: {
    id: "unternehmensregister",
    name: "Unternehmensregister",
    description: "Firmeninfo, Bilanzdaten (DE)",
    apps: ["openaccounting"],
    category: "tax",
    authType: "none",
    webhooks: false,
    rateLimitRPM: 10,
    requiredEnvVars: [],
    baseUrl: "https://www.unternehmensregister.de",
    docsUrl: "https://www.unternehmensregister.de/",
    icon: "unternehmensregister",
  },

  google_cloud_vision: {
    id: "google_cloud_vision",
    name: "Google Cloud Vision",
    description: "OCR + Belegklassifikation",
    apps: ["openaccounting"],
    category: "ocr",
    authType: "oauth2",
    webhooks: false,
    rateLimitRPM: 60,
    requiredEnvVars: ["GOOGLE_CLOUD_PROJECT_ID", "GOOGLE_CLOUD_CREDENTIALS"],
    baseUrl: "https://vision.googleapis.com/v1",
    docsUrl: "https://cloud.google.com/vision/docs",
    icon: "google_cloud",
    oauthTokenUrl: "https://oauth2.googleapis.com/token",
  },

} as const;

// ==================== Helper Functions ====================

export type IntegrationId = keyof typeof INTEGRATION_REGISTRY;

/** Get all integrations for a specific app */
export function getIntegrationsForApp(app: string): IntegrationDefinition[] {
  return Object.values(INTEGRATION_REGISTRY).filter((i) =>
    i.apps.includes(app as IntegrationDefinition["apps"][number])
  );
}

/** Get all integrations in a specific category */
export function getIntegrationsByCategory(category: string): IntegrationDefinition[] {
  return Object.values(INTEGRATION_REGISTRY).filter((i) => i.category === category);
}

/** Get a single integration by ID */
export function getIntegration(id: string): IntegrationDefinition | undefined {
  return INTEGRATION_REGISTRY[id as IntegrationId];
}

/** Get all integration IDs */
export function getAllIntegrationIds(): string[] {
  return Object.keys(INTEGRATION_REGISTRY);
}

/** Get count of integrations per app */
export function getIntegrationCountByApp(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const integration of Object.values(INTEGRATION_REGISTRY)) {
    for (const app of integration.apps) {
      counts[app] = (counts[app] ?? 0) + 1;
    }
  }
  return counts;
}
