export { DocumentAiClient } from "./client.js";
export type {
  DocumentAiClientConfig,
  DocumentAiMimeType,
  ProvenanceType,
  BatchOperationState,
  NormalizedVertex,
  BoundingPoly,
  TextAnchor,
  PageAnchor,
  DetectedLanguage,
  Layout,
  PageToken,
  PageLine,
  PageParagraph,
  PageBlock,
  TableCell,
  TableRow,
  PageTable,
  FormField,
  Page,
  Entity,
  NormalizedValue,
  Document,
  RawDocumentInput,
  GcsDocumentInput,
  ProcessRequest,
  ProcessResponse,
  BatchDocumentInput,
  BatchOutputConfig,
  BatchProcessRequest,
  BatchProcessOperation,
} from "./types.js";
