export { FigoClient } from "./client.js";
export type {
  FigoClientConfig,
  FinAPIConnectionStatus,
  FinAPIUpdateStatus,
  FinAPIAccountType,
  FinAPITransactionDirection,
  FinAPICategoryType,
  FinAPIBank,
  FinAPIBankConnection,
  FinAPIUpdateResult,
  FinAPIImportBankConnectionRequest,
  FinAPIImportBankConnectionResponse,
  FinAPIAccount,
  FinAPIAccountsResponse,
  FinAPIAccountsParams,
  FinAPITransaction,
  FinAPITransactionsResponse,
  FinAPITransactionsParams,
  FinAPICategory,
  FinAPICategoriesResponse,
  FinAPILabel,
  FinAPILabelsResponse,
  FinAPICategorizeTransactionsRequest,
  FinAPIPaging,
} from "./types.js";
