/**
 * SL1 Format Encoder
 *
 * The SL1 format used by Prusa SL1/SL1S printers is a ZIP archive containing:
 * - One PNG per layer (named 00001.png, 00002.png, etc.)
 * - prusaslicer.ini with print configuration
 *
 * This is the simplest resin printer format and can be converted
 * to other formats via UVtools.
 */

import type { SliceConfig, ResinPrinterProfile } from "../types";

export interface SL1Config {
  sliceConfig: SliceConfig;
  printerProfile: ResinPrinterProfile;
  layerCount: number;
  estimatedPrintTime: number;
  estimatedVolumeMl: number;
}

/**
 * Generate the prusaslicer.ini content for an SL1 file.
 */
export function generateSL1Config(config: SL1Config): string {
  const lines = [
    "; Generated by OpenSlicer",
    `; Printer: ${config.printerProfile.name}`,
    "",
    `action = print`,
    `jobDir = /`,
    `expTime = ${config.sliceConfig.exposureTime}`,
    `expTimeFirst = ${config.sliceConfig.bottomExposureTime}`,
    `layerHeight = ${config.sliceConfig.layerHeight}`,
    `numFade = ${config.sliceConfig.bottomLayers}`,
    `numFast = ${config.layerCount - config.sliceConfig.bottomLayers}`,
    `numSlow = ${config.sliceConfig.bottomLayers}`,
    `printTime = ${Math.round(config.estimatedPrintTime)}`,
    `usedMaterial = ${config.estimatedVolumeMl.toFixed(2)}`,
    `resolutionX = ${config.printerProfile.resolutionX}`,
    `resolutionY = ${config.printerProfile.resolutionY}`,
    `displayWidth = ${config.printerProfile.displayWidth}`,
    `displayHeight = ${config.printerProfile.displayHeight}`,
    `maxPrintHeight = ${config.printerProfile.buildHeight}`,
  ];

  return lines.join("\n") + "\n";
}

/**
 * Format a layer index as a zero-padded filename.
 * e.g., 0 -> "00001.png", 42 -> "00043.png"
 */
export function getLayerFilename(index: number): string {
  return String(index + 1).padStart(5, "0") + ".png";
}
