export { AWSSESClient } from "./client.js";
export type {
  AWSSESClientConfig,
  SESDestination,
  SESContent,
  SESBody,
  SESMessage,
  SESMessageTag,
  SESSendEmailRequest,
  SESSendEmailResponse,
  SESSendRawEmailRequest,
  SESSendRawEmailResponse,
  SESSendTemplatedEmailRequest,
  SESSendTemplatedEmailResponse,
  SESBulkEmailDestination,
  SESSendBulkTemplatedEmailRequest,
  SESBulkEmailStatus,
  SESSendBulkTemplatedEmailResponse,
  SESSendDataPoint,
  SESGetSendStatisticsResponse,
  SESGetSendQuotaResponse,
  SESVerifyEmailIdentityRequest,
  SESListIdentitiesResponse,
  SESGetIdentityVerificationAttributesResponse,
} from "./types.js";
