/**
 * Seed: OpenFarm Calibration Procedures — 22 Fuse 1 SLS calibration procedures
 */
import type { DbClient } from "../create-db";
import { farmCalibrationProcedures } from "../openfarm.schema";

export async function seedOpenfarmCalibration(db: DbClient) {
  const procedures = [
    // ==================== Tier 1: Core Calibrations ====================
    {
      id: "btmt",
      name: "Bed Temperature Measurement Tool (BTMT)",
      tier: "core" as const,
      technology: "sls" as const,
      description: "Print special .FLZ file with plaques at different temperature offsets. Visually inspect and select the best plaque to determine optimal bed temperature offset.",
      requiresPrint: true,
      estimatedDurationMinutes: 480,
      intervalPrints: 50,
      instructions: [
        { stepNumber: 1, title: "Download calibration file", description: "Download the material-specific .FLZ calibration file from Formlabs", type: "instruction" },
        { stepNumber: 2, title: "Insert clean build chamber", description: "Ensure a clean build chamber is installed", type: "instruction" },
        { stepNumber: 3, title: "Print calibration file", description: "Print the .FLZ file without modifications", type: "print", durationMinutes: 360 },
        { stepNumber: 4, title: "Cool down", description: "Allow at least 2 hours cooling before opening", type: "wait", durationMinutes: 120 },
        { stepNumber: 5, title: "Extract and inspect plaques", description: "Remove plaques and inspect for orange peel texture, dimpling, curling", type: "measure" },
        { stepNumber: 6, title: "Select best plaque", description: "Choose plaque with slight orange peel, no dimpling, no curling", type: "measure" },
        { stepNumber: 7, title: "Enter offset on touchscreen", description: "Navigate to Settings > Calibration and enter the selected temperature offset", type: "enter_on_touchscreen" },
        { stepNumber: 8, title: "Verify with production print", description: "Print a normal job and check quality", type: "verify" },
      ],
      sortOrder: 1,
    },
    {
      id: "xy_scaling",
      name: "X/Y Scaling Calibration",
      tier: "core" as const,
      technology: "sls" as const,
      description: "Print 24-point test piece, measure with digital calipers, and calculate X/Y correction percentages for horizontal dimensional accuracy (±150µm).",
      requiresPrint: true,
      estimatedDurationMinutes: 600,
      intervalPrints: 100,
      instructions: [
        { stepNumber: 1, title: "Update firmware", description: "Ensure printer firmware is up to date", type: "instruction" },
        { stepNumber: 2, title: "Download test file", description: "Download the X/Y scaling test file from PreForm", type: "instruction" },
        { stepNumber: 3, title: "Print without modifications", description: "Do NOT move, rescale, or reorient the test model", type: "print", durationMinutes: 360 },
        { stepNumber: 4, title: "Cool for 5h30min", description: "Wait until enclosure temperature drops below 35°C (95°F)", type: "wait", durationMinutes: 330 },
        { stepNumber: 5, title: "Extract and clean", description: "Carefully extract, clean thoroughly with Fuse Sift, and media blast", type: "instruction" },
        { stepNumber: 6, title: "Measure 24 points", description: "Use digital calipers, zero before starting, measure all 24 points on both sides", type: "measure" },
        { stepNumber: 7, title: "Enter measurements", description: "Enter all 24 measurements into the printer touchscreen calibration tool", type: "enter_on_touchscreen" },
        { stepNumber: 8, title: "Calculate and apply", description: "Tap Calculate to generate X/Y correction percentages", type: "enter_on_touchscreen" },
        { stepNumber: 9, title: "Verify with production print", description: "Print a dimensionally critical part to confirm accuracy", type: "verify" },
      ],
      sortOrder: 2,
    },
    {
      id: "z_scaling",
      name: "Z Scaling Calibration",
      tier: "core" as const,
      technology: "sls" as const,
      description: "Print Z test piece, measure heights, and calculate Z correction factor for vertical dimensional accuracy (±1% or 0.6mm).",
      requiresPrint: true,
      estimatedDurationMinutes: 540,
      intervalPrints: 100,
      calibrationModelPath: "/calibration/fuse1_z_calibration.stl",
      instructions: [
        { stepNumber: 1, title: "Download Z test file", description: "Download the Z scaling calibration file (Stufenblock 120×50×120mm, 6 Stufen à 20mm)", type: "instruction" },
        { stepNumber: 2, title: "Print without modifications", description: "Print the test file as-is", type: "print", durationMinutes: 360 },
        { stepNumber: 3, title: "Cool down", description: "Allow standard cooling procedure", type: "wait", durationMinutes: 120 },
        { stepNumber: 4, title: "Extract and clean", description: "Remove and clean test piece", type: "instruction" },
        { stepNumber: 5, title: "Measure heights", description: "Measure heights of test features with calipers or height gauge", type: "measure" },
        { stepNumber: 6, title: "Enter measurements", description: "Enter height measurements into the calibration tool", type: "enter_on_touchscreen" },
        { stepNumber: 7, title: "Apply correction factor", description: "The printer calculates the Z correction factor automatically", type: "enter_on_touchscreen" },
      ],
      sortOrder: 3,
    },
    {
      id: "diagnostic",
      name: "Diagnostic Test Print",
      tier: "core" as const,
      technology: "sls" as const,
      description: "Full-system evaluation print. Results evaluable on touchscreen (firmware 1.24.1+). Determines which specific calibrations are needed.",
      firmwareMinVersion: "1.24.1",
      requiresPrint: true,
      estimatedDurationMinutes: 480,
      intervalPrints: 200,
      instructions: [
        { stepNumber: 1, title: "Download diagnostic file", description: "Download the diagnostic print file from Formlabs", type: "instruction" },
        { stepNumber: 2, title: "Print diagnostic file", description: "Print without modifications", type: "print", durationMinutes: 360 },
        { stepNumber: 3, title: "Cool down", description: "Standard cooling procedure", type: "wait", durationMinutes: 120 },
        { stepNumber: 4, title: "Evaluate on touchscreen", description: "Use firmware evaluation tool to grade print results", type: "measure" },
        { stepNumber: 5, title: "Review recommendations", description: "Touchscreen shows which calibrations are needed", type: "instruction" },
      ],
      sortOrder: 4,
    },

    // ==================== Tier 2: Mechanical Calibrations ====================
    {
      id: "leveling",
      name: "Printer Leveling",
      tier: "mechanical" as const,
      technology: "sls" as const,
      description: "Accelerometer-based foot adjustment using the touchscreen. Required after physical relocation.",
      requiresPrint: false,
      estimatedDurationMinutes: 15,
      instructions: [
        { stepNumber: 1, title: "Access leveling", description: "Navigate to Settings > Calibration > Level Printer", type: "instruction" },
        { stepNumber: 2, title: "Adjust feet", description: "Insert flat-head screwdriver through stand holes, turn until touchscreen indicates level", type: "enter_on_touchscreen" },
      ],
      sortOrder: 10,
    },
    {
      id: "doser",
      name: "Doser Recalibration",
      tier: "mechanical" as const,
      technology: "sls" as const,
      description: "Recalibrate the powder dosing mechanism. Performed after doser replacement or service.",
      requiresPrint: false,
      estimatedDurationMinutes: 30,
      instructions: [
        { stepNumber: 1, title: "Access doser calibration", description: "Navigate to Settings > Calibration > Doser Calibration", type: "instruction" },
        { stepNumber: 2, title: "Follow touchscreen prompts", description: "The printer runs an automated doser calibration sequence", type: "enter_on_touchscreen", durationMinutes: 20 },
      ],
      sortOrder: 11,
    },
    {
      id: "powder_flipper",
      name: "Powder Flipper Calibration",
      tier: "mechanical" as const,
      technology: "sls" as const,
      description: "Calibrate recoater flipper alignment after flipper replacement to prevent collision.",
      requiresPrint: false,
      estimatedDurationMinutes: 20,
      instructions: [
        { stepNumber: 1, title: "Access flipper calibration", description: "Navigate to Settings > Calibration > Flipper Calibration", type: "instruction" },
        { stepNumber: 2, title: "Align flipper", description: "Push flipper down and parallel to ceiling, follow touchscreen prompts", type: "enter_on_touchscreen" },
      ],
      sortOrder: 12,
    },

    // ==================== Tier 3: Maintenance Affecting Calibration ====================
    {
      id: "optical_cassette_clean",
      name: "Optical Cassette Cleaning",
      tier: "maintenance" as const,
      technology: "sls" as const,
      description: "Clean laser/camera windows on the optical cassette. Dirty windows attenuate laser power, mimicking laser degradation.",
      requiresPrint: false,
      estimatedDurationMinutes: 15,
      intervalPrints: 1,
      instructions: [
        { stepNumber: 1, title: "Remove optical cassette", description: "Open printer top, remove optical cassette", type: "instruction" },
        { stepNumber: 2, title: "Inspect windows", description: "Check for powder deposits, laurolactam buildup", type: "instruction" },
        { stepNumber: 3, title: "Clean windows", description: "Use provided cleaning tools and wipes", type: "instruction" },
        { stepNumber: 4, title: "Reinstall", description: "Reinstall optical cassette", type: "instruction" },
      ],
      sortOrder: 20,
    },
    {
      id: "ir_sensor_clean",
      name: "IR Sensor / Housing Cleaning",
      tier: "maintenance" as const,
      technology: "sls" as const,
      description: "Clean IR sensor and housing. Dirty sensor gives wrong temperature readings, invalidating bed temperature calibration.",
      requiresPrint: false,
      estimatedDurationMinutes: 10,
      intervalPrints: 5,
      intervalHours: 100,
      instructions: [
        { stepNumber: 1, title: "Locate IR sensor", description: "Find the IR sensor housing inside the print enclosure", type: "instruction" },
        { stepNumber: 2, title: "Clean housing", description: "Clean exterior of sensor housing", type: "instruction" },
        { stepNumber: 3, title: "Clean lens", description: "Gently clean the IR sensor lens", type: "instruction" },
      ],
      sortOrder: 21,
    },
    {
      id: "laser_window_clean",
      name: "Upper Laser Window Cleaning",
      tier: "maintenance" as const,
      technology: "sls" as const,
      description: "Clean the fixed window above the galvo mirrors. Laurolactam buildup reduces laser transmission.",
      requiresPrint: false,
      estimatedDurationMinutes: 30,
      intervalHours: 1000,
      instructions: [
        { stepNumber: 1, title: "Access upper window", description: "Open printer panels to access the fixed laser window", type: "instruction" },
        { stepNumber: 2, title: "Inspect for buildup", description: "Check for laurolactam or powder residue", type: "instruction" },
        { stepNumber: 3, title: "Clean window", description: "Clean using appropriate optical cleaning supplies", type: "instruction" },
      ],
      sortOrder: 22,
    },
    {
      id: "camera_lens_clean",
      name: "Camera Lens Cleaning",
      tier: "maintenance" as const,
      technology: "sls" as const,
      description: "Clean the monitoring camera lens. Affects print monitoring and diagnostic print evaluation.",
      requiresPrint: false,
      estimatedDurationMinutes: 10,
      intervalHours: 500,
      instructions: [
        { stepNumber: 1, title: "Locate camera", description: "Find the monitoring camera inside the enclosure", type: "instruction" },
        { stepNumber: 2, title: "Clean lens", description: "Gently clean the camera lens", type: "instruction" },
      ],
      sortOrder: 23,
    },
    {
      id: "exhaust_filter_clean",
      name: "Exhaust / Intake Filter Cleaning",
      tier: "maintenance" as const,
      technology: "sls" as const,
      description: "Clean or replace exhaust and intake air filters. Clogged filters affect chamber atmosphere.",
      requiresPrint: false,
      estimatedDurationMinutes: 20,
      intervalHours: 30,
      instructions: [
        { stepNumber: 1, title: "Access filters", description: "Open filter access panels", type: "instruction" },
        { stepNumber: 2, title: "Clean or replace", description: "Clean reusable filters or replace disposable ones", type: "instruction" },
      ],
      sortOrder: 24,
    },
    {
      id: "enclosure_clean",
      name: "Print Enclosure Cleaning",
      tier: "maintenance" as const,
      technology: "sls" as const,
      description: "Clean the print enclosure interior. Powder buildup can affect temperature distribution.",
      requiresPrint: false,
      estimatedDurationMinutes: 30,
      intervalHours: 100,
      instructions: [
        { stepNumber: 1, title: "Cool printer", description: "Ensure printer is cool before cleaning", type: "wait" },
        { stepNumber: 2, title: "Vacuum enclosure", description: "Vacuum loose powder from all surfaces", type: "instruction" },
        { stepNumber: 3, title: "Wipe surfaces", description: "Wipe down enclosure walls and floor", type: "instruction" },
      ],
      sortOrder: 25,
    },
    {
      id: "exhaust_purge",
      name: "Exhaust Line Purging",
      tier: "maintenance" as const,
      technology: "sls" as const,
      description: "Purge exhaust lines to prevent powder clogging. Blocked exhaust affects chamber atmosphere.",
      requiresPrint: false,
      estimatedDurationMinutes: 30,
      intervalHours: 500,
      instructions: [
        { stepNumber: 1, title: "Access exhaust lines", description: "Locate exhaust line connections", type: "instruction" },
        { stepNumber: 2, title: "Purge lines", description: "Run purge procedure to clear powder deposits", type: "instruction" },
      ],
      sortOrder: 26,
    },

    // ==================== Tier 4: Service-Only ====================
    {
      id: "laser_module",
      name: "Laser Module Replacement",
      tier: "service" as const,
      technology: "sls" as const,
      description: "Replace laser module when parts are fragile, lighter color, granular texture despite clean optics. Requires Formlabs service.",
      requiresPrint: false,
      estimatedDurationMinutes: 120,
      sortOrder: 30,
    },
    {
      id: "galvo_alignment",
      name: "Galvanometer / Mirror Alignment",
      tier: "service" as const,
      technology: "sls" as const,
      description: "Factory-calibrated galvo mirrors. Required if X/Y scaling can't correct errors, or after shipping damage. Requires Formlabs service.",
      requiresPrint: false,
      estimatedDurationMinutes: 120,
      sortOrder: 31,
    },
    {
      id: "piston_seal",
      name: "Build Chamber Piston Seal",
      tier: "service" as const,
      technology: "sls" as const,
      description: "Replace the build chamber piston seal. Affects Z-axis accuracy. Requires Formlabs service.",
      requiresPrint: false,
      estimatedDurationMinutes: 90,
      sortOrder: 32,
    },
    {
      id: "ir_sensor_replace",
      name: "IR Sensor Replacement",
      tier: "service" as const,
      technology: "sls" as const,
      description: "Replace the IR temperature sensor. After replacement, BTMT recalibration is required. Requires Formlabs service.",
      requiresPrint: false,
      estimatedDurationMinutes: 60,
      sortOrder: 33,
    },
    {
      id: "accelerometer_recal",
      name: "Accelerometer Recalibration",
      tier: "service" as const,
      technology: "sls" as const,
      description: "Recalibrate the internal accelerometer when leveling drift occurs without physical movement. Requires Formlabs service.",
      requiresPrint: false,
      estimatedDurationMinutes: 30,
      sortOrder: 34,
    },

    // ==================== Software Tuning ====================
    {
      id: "powder_refresh_rate",
      name: "Powder Refresh Rate",
      tier: "software" as const,
      technology: "sls" as const,
      description: "Set the ratio of fresh to recycled powder in PreForm. Nylon 12: 30% fresh, Nylon 12 GF: 50% fresh.",
      requiresPrint: false,
      estimatedDurationMinutes: 5,
      sortOrder: 40,
    },
    {
      id: "bed_temp_override",
      name: "Bed Target Temperature Override",
      tier: "software" as const,
      technology: "sls" as const,
      description: "Direct temperature target override on the printer touchscreen, separate from the BTMT calibration tool.",
      requiresPrint: false,
      estimatedDurationMinutes: 5,
      sortOrder: 41,
    },
    {
      id: "nitrogen_setup",
      name: "Nitrogen Atmosphere Setup (Fuse 1+ only)",
      tier: "software" as const,
      technology: "sls" as const,
      description: "Set up inert atmosphere printing with external nitrogen source. Physical hookup + controller configuration. Fuse 1+ exclusive.",
      requiresPrint: false,
      estimatedDurationMinutes: 60,
      sortOrder: 42,
    },
  ];

  for (const proc of procedures) {
    await db.insert(farmCalibrationProcedures).values(proc).onConflictDoNothing();
  }

  return { procedureCount: procedures.length };
}
